# Exploring and Clean Data of the CIC-IDS-2018 Dataset
[official dataset link](https://www.unb.ca/cic/datasets/ids-2018.html)


Based on the following exploration; The __"Friday-02-03-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Friday-16-02-2018_TrafficForML_CICFlowMeter.csv"__, __"Friday-02-23-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv"__, __"Thursday-02-15-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Thursday-02-22-2018_TrafficForML_CICFlowMeter.csv"__, __"Tuesday-02-20-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Wednesday-02-14-2018_TrafficForML_CICFlowMeter.csv"__, __"Wednesday-02-21-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Wednesday-02-28-2018_TrafficForML_CICFlowMeter.csv"__ csv files were chosen with the following labels:
* __Benign__ (1,209,156 total instances)
* __Bot__ (286,191 total instances)
* __DoS attacks-SlowHTTPTest__ (139,890 total instances)
* __DoS attacks-Hulk__ (461,912 total instances)
* __Brute Force -Web__ (1,209,156 total instances)
* __Brute Force -XSS__ (286,191 total instances)
* __SQL Injection__ (139,890 total instances)
* __DDoS attacks-LOIC-HTTP__ (461,912 total instances)
* __DoS attacks-GoldenEye__ (1,209,156 total instances)
* __Infilteration__ (286,191 total instances)
* __DoS attacks-Slowloris__ (139,890 total instances)
* __FTP-BruteForce__ (461,912 total instances)
* __SSH-Bruteforce__ (1,209,156 total instances)
* __DDOS attack-LOIC-UDP__ (286,191 total instances)
* __DDOS attack-HOIC__ (139,890 total instances)
* Label (one erroneous row, would need to be removed)

__Reasoning__: The labels are better balanced than the rest of the files. For the purposes of a baseline experiment; it would be satisfactory.

The __Bot__, __DoS attacks-SlowHTTPTest__, __DoS attacks-Hulk__, __Brute Force -Web__, __Brute Force -XSS__, __SQL Injection__, __DDoS attacks-LOIC-HTTP__, __DoS attacks-GoldenEye__, __Infilteration__, __DoS attacks-Slowloris__, __FTP-BruteForce__, __SSH-Bruteforce__, __DDOS attack-LOIC-UDP__, __DDOS attack-HOIC__ labels would be combined into one __"Malicious"__ label for a total of 887,993 __"Malicious"__ instances

The baseline experiment would be a binary classification experiment between __236,421 "Malicious"__ instances vs __63,489 "Benign"__ instances.

....

In [ ]:
hdkasjdkasjdlkasj

### 1- Friday logs

In [40]:
import pandas as pd

#### 1.1- Friday-02-03-2018_TrafficForML_CICFlowMeter.csv

In [86]:
df_friday1 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/03-02-2018.csv')

In [87]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [88]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [89]:
df_friday1["Label"].unique()

array(['Benign', 'Bot'], dtype=object)

In [90]:
print(df_friday1["Label"].value_counts()[['Benign']].sum())
print(df_friday1["Label"].value_counts()[['Bot']].sum())

762384
286191

In [91]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [92]:
df_friday1["Label"].unique()

array(['Benign', 'Bot'], dtype=object)

### 2- Removing row with erroneous 'Label' label

In [93]:
# Remove erroneous 'Label' row
df_friday1.drop(df_friday1.loc[df_friday1["Label"] == "Label"].index, inplace=True)

In [94]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [95]:
df_friday1.replace(to_replace=['Bot'], value="Malicious", inplace=True)

In [96]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [97]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [98]:
print(df_friday1["Label"].value_counts()[['Benign']].sum())
print(df_friday1["Label"].value_counts()[['Malicious']].sum())

762384
286191

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [99]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [100]:
df_friday1["Protocol"].unique()

array([ 6,  0, 17])

In [101]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [102]:
# Forcing them to be strings
df_friday1 = df_friday1.astype({"Protocol": str})

In [103]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [104]:
df_friday1["Protocol"].unique()

array(['6', '0', '17'], dtype=object)

In [105]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [106]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [107]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [108]:
# making Label column the last column again
df_friday1.insert(len(df_friday1.columns)-1, 'Label', df_friday1.pop('Label'))

In [110]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [111]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [112]:
df_friday1.drop(columns=columns_to_drop, inplace=True)

In [114]:
df_friday1

,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444444,87.534438,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,6,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,6,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,6,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,6,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,6,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,6,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,6,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

### 6- Dropping missing or duplicate values

In [115]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [116]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [118]:
df_friday1

,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444444,87.534438,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,6,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,6,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,6,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,6,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,6,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,6,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,6,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [119]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [120]:
df_friday1.drop_duplicates(inplace=True)

In [122]:
df_friday1

,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444444,87.534438,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,6,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,6,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,6,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,6,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,6,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,6,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,6,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [123]:
print(df_friday1["Label"].value_counts()[['Benign']].sum())
print(df_friday1["Label"].value_counts()[['Malicious']].sum())

627628
144535

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [124]:
df_friday1.replace(to_replace="Benign", value=0, inplace=True)
df_friday1.replace(to_replace="Malicious", value=1, inplace=True)

In [127]:
df_friday1

,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444444,87.534438,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,6,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,6,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,6,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048571,6,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048572,6,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048573,6,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048574,6,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [128]:
print(df_friday1["Label"].value_counts()[[0]].sum())
print(df_friday1["Label"].value_counts()[[1]].sum())

627628
144535

### 9- Saving dataset

In [132]:
df_friday1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 772163 entries, 0 to 1048574
Data columns (total 72 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Protocol           772163 non-null  object
 1   Flow Duration      772163 non-null  int64
 2   Tot Fwd Pkts       772163 non-null  int64
 3   Tot Bwd Pkts       772163 non-null  int64
 4   TotLen Fwd Pkts    772163 non-null  int64
 5   TotLen Bwd Pkts    772163 non-null  float64
 6   Fwd Pkt Len Max    772163 non-null  int64
 7   Fwd Pkt Len Min    772163 non-null  int64
 8   Fwd Pkt Len Mean   772163 non-null  float64
 9   Fwd Pkt Len Std    772163 non-null  float64
 10  Bwd Pkt Len Max    772163 non-null  int64
 11  Bwd Pkt Len Min    772163 non-null  int64
 12  Bwd Pkt Len Mean   772163 non-null  float64
 13  Bwd Pkt Len Std    772163 non-null  float64
 14  Flow IAT Mean      772163 non-null  float64
 15  Flow IAT Std       772163 non-null  float64
 16  Flow IAT Max       772163 non-null  float64
 17  Flow IAT Min       772163 non-null  float64
 18  Fwd IAT Tot        772163 non-null  float64
 19  Fwd IAT Mean       772163 non-null  float64
 20  Fwd IAT Std        772163 non-null  float64
 21  Fwd IAT Max        772163 non-null  float64
 22  Fwd IAT Min        772163 non-null  float64
 23  Bwd IAT Tot        772163 non-null  float64
 24  Bwd IAT Mean       772163 non-null  float64
 25  Bwd IAT Std        772163 non-null  float64
 26  Bwd IAT Max        772163 non-null  float64
 27  Bwd IAT Min        772163 non-null  float64
 28  Fwd Header Len     772163 non-null  int64
 29  Bwd Header Len     772163 non-null  int64
 30  Fwd Pkts/s         772163 non-null  float64
 31  Bwd Pkts/s         772163 non-null  float64
 32  Pkt Len Min        772163 non-null  int64
 33  Pkt Len Max        772163 non-null  int64
 34  Pkt Len Mean       772163 non-null  float64
 35  Pkt Len Std        772163 non-null  float64
 36  Pkt Len Var        772163 non-null  float64
 37  FIN Flag Cnt       772163 non-null  int64
 38  SYN Flag Cnt       772163 non-null  int64
 39  RST Flag Cnt       772163 non-null  int64
 40  PSH Flag Cnt       772163 non-null  int64
 41  ACK Flag Cnt       772163 non-null  int64
 42  URG Flag Cnt       772163 non-null  int64
 43  CWE Flag Count     772163 non-null  int64
 44  ECE Flag Cnt       772163 non-null  int64
 45  Down/Up Ratio      772163 non-null  int64
 46  Pkt Size Avg       772163 non-null  float64
 47  Fwd Seg Size Avg   772163 non-null  float64
 48  Bwd Seg Size Avg   772163 non-null  float64
 49  Fwd Byts/b Avg     772163 non-null  int64
 50  Fwd Pkts/b Avg     772163 non-null  int64
 51  Fwd Blk Rate Avg   772163 non-null  int64
 52  Bwd Byts/b Avg     772163 non-null  int64
 53  Bwd Pkts/b Avg     772163 non-null  int64
 54  Bwd Blk Rate Avg   772163 non-null  int64
 55  Subflow Fwd Pkts   772163 non-null  int64
 56  Subflow Fwd Byts   772163 non-null  int64
 57  Subflow Bwd Pkts   772163 non-null  int64
 58  Subflow Bwd Byts   772163 non-null  int64
 59  Init Fwd Win Byts  772163 non-null  int64
 60  Init Bwd Win Byts  772163 non-null  int64
 61  Fwd Act Data Pkts  772163 non-null  int64
 62  Fwd Seg Size Min   772163 non-null  int64
 63  Active Mean        772163 non-null  float64
 64  Active Std         772163 non-null  float64
 65  Active Max         772163 non-null  float64
 66  Active Min         772163 non-null  float64
 67  Idle Mean          772163 non-null  float64
 68  Idle Std           772163 non-null  float64
 69  Idle Max           772163 non-null  float64
 70  Idle Min           772163 non-null  float64
 71  Label              772163 non-null  int64
dtypes: float64(35), int64(36), object(1)
memory usage: 430.1+ MB

In [135]:
print(df_friday1["Label"].value_counts()[[0]].sum())
print(df_friday1["Label"].value_counts()[[1]].sum())

627628
144535

In [138]:
df_friday1_benign =  df_friday1[df_friday1["Label"]==0]
df_friday1_benign

,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444444,87.534438,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,6,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,6,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,6,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048571,6,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048572,6,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048573,6,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1048574,6,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [ ]:
df_friday1_malicious = df_friday1[df_friday1["Label"]==1]
df_friday1_

#### 1.2- Friday-16-02-2018_TrafficForML_CICFlowMeter.csv

In [9]:
df_friday2 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-16-2018.csv', low_memory=False)

In [10]:
df_friday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,...,0,0,0,0,0,56300000,138.5929291,56300000,56300000,Benign
1,0,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,...,0,0,0,0,0,56300000,263.7508294,56300000,56300000,Benign
2,35605,6,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,...,20,2624734,0,2624734,2624734,9058214,0,9058214,9058214,Benign
3,0,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,...,0,0,0,0,0,56300000,82.02438662,56300000,56300000,Benign
4,23,6,16/02/2018 08:27:59,20,1,1,0,0,0,0,...,20,0,0,0,0,0,0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048571,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048572,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048573,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048574,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest

In [11]:
df_friday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [12]:
df_friday2["Label"].unique()

array(['Benign', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Hulk', 'Label'],
      dtype=object)

In [13]:
print(df_friday2["Label"].value_counts()[['Benign']].sum())
print(df_friday2["Label"].value_counts()[['DoS attacks-SlowHTTPTest']].sum())
print(df_friday2["Label"].value_counts()[['DoS attacks-Hulk']].sum())
print(df_friday2["Label"].value_counts()[['Label']].sum())

446772
139890
461912
1

In [14]:
df_friday2.loc[df_friday2["Label"] == "Label"]

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
999999,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label

In [15]:
# cut only benign 
df2_benign = df_friday2.loc[df_friday2['Label'] == 'Benign']
print(df2_benign.shape[0])

# cut only DoS attacks-SlowHTTPTest
df2_dos_slowhttptest = df_friday2.loc[df_friday2['Label'] == 'DoS attacks-SlowHTTPTest']
print(df2_dos_slowhttptest.shape[0])

# cut only DoS attacks-Hulk
df2_dos_hulk = df_friday2.loc[df_friday2['Label'] == 'DoS attacks-Hulk']
print(df2_dos_hulk.shape[0])

446772
139890
461912

In [16]:
# take 446772 benign 
print(df2_benign.shape[0])

# take 69945 Dos attacks-SlowHTTPTest
df2_dos_slowhttptest = df2_dos_slowhttptest.head(69945)
print(df2_dos_slowhttptest.shape[0])

# take 23334 DoS attacks - Hulk 
df2_dos_hulk = df2_dos_hulk.head(23334)
print(df2_dos_hulk.shape[0])

446772
69945
23334

#### 1.3 Friday-23-02-2018_TrafficForML_CICFlowMeter.csv

In [17]:
df_friday3 = pd.read_csv('/mnt/d/project-chau/dataset/\
cse-cic-ids108/dataset/02-23-2018.csv')

In [18]:
df_friday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,23/02/2018 08:18:29,1532698,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1,500,17,23/02/2018 08:17:45,117573855,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,Benign
2,500,17,23/02/2018 08:17:45,117573848,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,Benign
3,22,6,23/02/2018 08:19:55,1745392,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
4,500,17,23/02/2018 08:18:17,89483474,6,0,3000,0,500,500,...,8,4000364.0,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,54116,6,23/02/2018 09:00:54,85992425,2,0,0,0,0,0,...,20,0.0,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,Benign
1048571,33914,6,23/02/2018 12:31:42,132,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048572,53,17,23/02/2018 12:15:24,79134,1,1,41,98,41,41,...,8,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048573,3389,6,23/02/2018 12:45:39,10053785,11,12,1321,1659,677,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048574,445,6,23/02/2018 09:04:11,566835,6,5,455,338,140,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign

In [19]:
df_friday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [20]:
df_friday3["Label"].unique()

array(['Benign', 'Brute Force -Web', 'Brute Force -XSS', 'SQL Injection'],
      dtype=object)

In [21]:
print(df_friday3["Label"].value_counts()[['Benign']].sum())
print(df_friday3["Label"].value_counts()[['Brute Force -Web']].sum())
print(df_friday3["Label"].value_counts()[['Brute Force -XSS']].sum())
print(df_friday3["Label"].value_counts()[['SQL Injection']].sum())

1048009
362
151
53

In [22]:
# cut only benign 
df3_benign = df_friday3.loc[df_friday3['Label'] == 'Benign']
print(df3_benign.shape[0])

# cut only Brute Force -Web
df3_brute_forceweb = df_friday3.loc[df_friday3['Label'] == 'Brute Force -Web']
print(df3_brute_forceweb.shape[0])

# cut only Brute Force -XSS 
df3_brute_forcexss = df_friday3.loc[df_friday3['Label'] == 'Brute Force -XSS']
print(df3_brute_forcexss.shape[0])

# cut only SQL Injection 
df3_sqlinjection = df_friday3.loc[df_friday3['Label'] == 'SQL Injection']
print(df3_sqlinjection.shape[0])

1048009
362
151
53

In [23]:
# take 1048009 benign
print(df3_benign.shape[0])

# take 362 Brute Force -Web
print(df3_brute_forceweb.shape[0])

# take 151 Brute Force -XSS 
print(df3_brute_forcexss.shape[0])

# take 53 SQL Injection
print(df3_sqlinjection.shape[0])

1048009
362
151
53

### 2- Thursday logs

#### 2.1 Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv

In [24]:
import pandas as pd

In [25]:
df_thursday1 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-20-2018.csv', low_memory=False)

In [26]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,22,6,20/02/2018 08:34:07,888751,11,11,...,32,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:33:22,112642816,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:36:11,112642712,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:39:00,112642648,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:41:49,112642702,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,443,6,20/02/2018 01:57:49,5129181,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,443,6,20/02/2018 01:57:49,5129544,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,443,6,20/02/2018 01:57:49,5130113,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,51849,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,51848,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign

In [27]:
df_thursday1.columns

Index(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [28]:
df_thursday1["Label"].unique()

array(['Benign', 'DDoS attacks-LOIC-HTTP'], dtype=object)

In [29]:
print(df_thursday1["Label"].value_counts()[['Benign']].sum())
print(df_thursday1["Label"].value_counts()[['DDoS attacks-LOIC-HTTP']].sum())

468277
576191

In [30]:
# cut only benign 
df4_benign = df_thursday1.loc[df_thursday1['Label'] == 'Benign']
print(df4_benign.shape[0])

# cut only DDoS attacks-LOIC-HTTP
df4_DDoS_loichttp = df_thursday1.loc[df_thursday1['Label'] == 'DDoS attacks-LOIC-HTTP']
print(df4_DDoS_loichttp.shape[0])

468277
576191

In [31]:
# take 468277 benign
print(df4_benign.shape[0])

# take 28810 DDoS attacks-LOIC-HTTP
df4_DDoS_loichttp = df4_DDoS_loichttp.head(28810)
print(df4_DDoS_loichttp.shape[0])

468277
28810

#### 2.2 Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv

In [32]:
import pandas as pd

In [33]:
df_thursday2 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/03-01-2018.csv')

In [34]:
df_thursday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,1/3/2018 8:17,115307855,5,0,0,0,0,0,...,0,1812348.0,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,Benign
1,0,0,1/3/2018 8:20,60997457,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
2,67,17,1/3/2018 8:17,61149019,5,0,1500,0,300,300,...,8,3530939.0,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,Benign
3,0,0,1/3/2018 8:22,60997555,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
4,0,0,1/3/2018 8:24,61997503,3,0,0,0,0,0,...,0,999909.0,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,0,0,1/3/2018 12:59,118494070,31,0,0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331096,2634,6,1/3/2018 12:59,114340,2,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331097,3389,6,1/3/2018 12:59,1404866,8,7,1132,1581,661,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331098,3389,6,1/3/2018 12:59,3966663,14,7,1386,392,680,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331099,53092,6,1/3/2018 12:59,86637706,2,0,0,0,0,0,...,20,0.0,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,Benign

In [35]:
df_thursday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [36]:
df_thursday2["Label"].unique()

array(['Benign', 'Infilteration'], dtype=object)

In [37]:
print(df_thursday2["Label"].value_counts()[['Benign']].sum())
# print(df_thursday2["Label"].value_counts()[['Label']].sum())
print(df_thursday2["Label"].value_counts()[['Infilteration']].sum())

238037
93063

In [38]:
df_thursday2.loc[df_thursday2["Label"] == "Label"]

Empty DataFrame
Columns: [Dst Port, Protocol, Timestamp, Flow Duration, Tot Fwd Pkts, Tot Bwd Pkts, TotLen Fwd Pkts, TotLen Bwd Pkts, Fwd Pkt Len Max, Fwd Pkt Len Min, Fwd Pkt Len Mean, Fwd Pkt Len Std, Bwd Pkt Len Max, Bwd Pkt Len Min, Bwd Pkt Len Mean, Bwd Pkt Len Std, Flow Byts/s, Flow Pkts/s, Flow IAT Mean, Flow IAT Std, Flow IAT Max, Flow IAT Min, Fwd IAT Tot, Fwd IAT Mean, Fwd IAT Std, Fwd IAT Max, Fwd IAT Min, Bwd IAT Tot, Bwd IAT Mean, Bwd IAT Std, Bwd IAT Max, Bwd IAT Min, Fwd PSH Flags, Bwd PSH Flags, Fwd URG Flags, Bwd URG Flags, Fwd Header Len, Bwd Header Len, Fwd Pkts/s, Bwd Pkts/s, Pkt Len Min, Pkt Len Max, Pkt Len Mean, Pkt Len Std, Pkt Len Var, FIN Flag Cnt, SYN Flag Cnt, RST Flag Cnt, PSH Flag Cnt, ACK Flag Cnt, URG Flag Cnt, CWE Flag Count, ECE Flag Cnt, Down/Up Ratio, Pkt Size Avg, Fwd Seg Size Avg, Bwd Seg Size Avg, Fwd Byts/b Avg, Fwd Pkts/b Avg, Fwd Blk Rate Avg, Bwd Byts/b Avg, Bwd Pkts/b Avg, Bwd Blk Rate Avg, Subflow Fwd Pkts, Subflow Fwd Byts, Subflow Bwd Pkts, Subflow Bwd Byts, Init Fwd Win Byts, Init Bwd Win Byts, Fwd Act Data Pkts, Fwd Seg Size Min, Active Mean, Active Std, Active Max, Active Min, Idle Mean, Idle Std, Idle Max, Idle Min, Label]
Index: []

[0 rows x 80 columns]

In [39]:
# cut only benign 
df5_benign = df_thursday2.loc[df_thursday2['Label'] == 'Benign']
print(df5_benign.shape[0])

# cut only Infilteration
df5_infilteration = df_thursday2.loc[df_thursday2['Label'] == 'Infilteration']
print(df5_infilteration.shape[0])

238037
93063

In [40]:
# take 238037 benign
print(df5_benign.shape[0])

# take 4049 Infilteration
df5_infilteration = df5_infilteration.head(4049)
print(df5_infilteration.shape[0])

238037
4049

#### 2.3 Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv

In [41]:
df_thursday3 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-15-2018.csv')

In [42]:
df_thursday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,15/02/2018 08:25:18,112641158,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,Benign
1,22,6,15/02/2018 08:29:05,37366762,14,12,2168,2993,712,0,...,32,1024353.0,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,Benign
2,47514,6,15/02/2018 08:29:42,543,2,0,64,0,64,0,...,32,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
3,0,0,15/02/2018 08:28:07,112640703,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,Benign
4,0,0,15/02/2018 08:30:56,112640874,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,50111,6,15/02/2018 09:04:42,22,3,0,31,0,31,0,...,20,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
1048571,443,6,15/02/2018 09:03:55,54682783,5,1,123,46,46,0,...,20,158783.0,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,Benign
1048572,443,6,15/02/2018 09:03:56,53682093,5,1,123,46,46,0,...,20,259719.0,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,Benign
1048573,443,6,15/02/2018 09:03:55,54683364,5,1,123,46,46,0,...,20,158870.0,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,Benign
1048574,443,6,15/02/2018 09:02:01,116857161,18,17,1066,5265,281,0,...,20,221407.0,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,Benign

In [43]:
df_thursday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [44]:
df_thursday3["Label"].unique()

array(['Benign', 'DoS attacks-GoldenEye', 'DoS attacks-Slowloris'],
      dtype=object)

In [45]:
print(df_thursday3["Label"].value_counts()[['Benign']].sum())
print(df_thursday3["Label"].value_counts()[['DoS attacks-GoldenEye']].sum())
print(df_thursday3["Label"].value_counts()[['DoS attacks-Slowloris']].sum())

996077
41508
10990

In [46]:
# cut only benign 
df6_benign = df_thursday3.loc[df_thursday3['Label'] == 'Benign']
print(df6_benign.shape[0])

# cut only DoS attacks-GoldenEye
df6_dos_goldeneye = df_thursday3.loc[df_thursday3['Label'] == 'DoS attacks-GoldenEye']
print(df6_dos_goldeneye.shape[0])

# cut only DoS attacks-Slowloris
df6_dos_slowloris = df_thursday3.loc[df_thursday3['Label'] == 'DoS attacks-Slowloris']
print(df6_dos_slowloris.shape[0])

996077
41508
10990

In [47]:
# take 996077 benign
print(df6_benign.shape[0])

# take 20754 DoS attacks-GoldenEye
df6_dos_goldeneye = df6_dos_goldeneye.head(20754)
print(df6_dos_goldeneye.shape[0])

# take 5495 DoS attacks-Slowloris
df6_dos_slowloris = df6_dos_slowloris.head(5495)
print(df6_dos_slowloris.shape[0])

996077
20754
5495

#### 2.4 Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv

In [48]:
df_thursday4 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-22-2018.csv')

In [49]:
df_thursday4

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,...,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,...,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,17,22/02/2018 09:57:34,61898,2,2,78,254,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048571,1500,6,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,...,20,0.0,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign
1048572,53,17,22/02/2018 03:52:37,642,1,1,39,67,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048573,53,17,22/02/2018 09:40:42,78472,1,1,32,121,32,32,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048574,3389,6,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign

In [51]:
df_thursday4.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [52]:
df_thursday4["Label"].unique()

array(['Benign', 'Brute Force -Web', 'Brute Force -XSS', 'SQL Injection'],
      dtype=object)

In [53]:
print(df_thursday4["Label"].value_counts()[['Benign']].sum())
print(df_thursday4["Label"].value_counts()[['Brute Force -Web']].sum())
print(df_thursday4["Label"].value_counts()[['Brute Force -XSS']].sum())
print(df_thursday4["Label"].value_counts()[['SQL Injection']].sum())

1048213
249
79
34

In [54]:
# cut only benign 
df7_benign = df_thursday4.loc[df_thursday4['Label'] == 'Benign']
print(df7_benign.shape[0])

# cut only Brute Force -Web
df7_bruteforce_web = df_thursday4.loc[df_thursday4['Label'] == 'Brute Force -Web']
print(df7_bruteforce_web.shape[0])

# cut only Brute Force -XSS
df7_bruteforce_xss = df_thursday4.loc[df_thursday4['Label'] == 'Brute Force -XSS']
print(df7_bruteforce_xss.shape[0])

# cut only SQL Injection
df7_sql_injection = df_thursday4.loc[df_thursday4['Label'] == 'SQL Injection']
print(df7_sql_injection.shape[0])

249
79
34

In [55]:
# take benign
print(df7_benign.shape[0])

# take 249 Brute Force -Web
print(df7_bruteforce_web.shape[0])

# take 79 Brute Force -XSS
print(df7_bruteforce_xss.shape[0])

# take 34 SQL Injection
print(df7_sql_injection.shape[0])

249
79
34

### 3- Wednesday logs

#### 3.1 Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv

In [56]:
df_wednesday1 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-14-2018.csv')

In [57]:
df_wednesday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign

In [58]:
df_wednesday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [59]:
df_wednesday1["Label"].unique()

array(['Benign', 'FTP-BruteForce', 'SSH-Bruteforce'], dtype=object)

In [60]:
print(df_wednesday1["Label"].value_counts()[['Benign']].sum())
print(df_wednesday1["Label"].value_counts()[['FTP-BruteForce']].sum())
print(df_wednesday1["Label"].value_counts()[['SSH-Bruteforce']].sum())

667626
193360
187589

In [61]:
# cut only benign 
df8_benign = df_wednesday1.loc[df_wednesday1['Label'] == 'Benign']
print(df8_benign.shape[0])

# cut only FTP BruteForce
df8_ftp_bruteforce = df_wednesday1.loc[df_wednesday1['Label'] == 'FTP-BruteForce']
print(df8_ftp_bruteforce.shape[0])

# cut only SSH BruteForce
df8_ssh_bruteforce = df_wednesday1.loc[df_wednesday1['Label'] == 'SSH-Bruteforce']
print(df8_ssh_bruteforce.shape[0])

193360
187589

In [62]:
# take benign
print(df8_benign.shape[0])

# take 19336 FTP Brute Force
df8_ftp_bruteforce = df8_ftp_bruteforce.head(19336)
print(df8_ftp_bruteforce.shape[0])

# take 9380 SSH Brute Force
df8_ssh_bruteforce = df8_ssh_bruteforce.head(9380)
print(df8_ssh_bruteforce.shape[0])

19336
9380

#### 3.2 Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv

In [63]:
df_wednesday2 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-21-2018.csv')

In [64]:
df_wednesday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,6,21/02/2018 08:33:25,37953,5,3,135,127,135,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,500,17,21/02/2018 08:33:06,117573474,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58800000.0,23800000.0,75600000,42000000,Benign
2,500,17,21/02/2018 08:33:06,117573474,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58800000.0,23800000.0,75600000,42000000,Benign
3,500,17,21/02/2018 08:33:11,99743998,5,0,2500,0,500,500,...,8,4000290.0,0.0,4000290,4000290,31900000.0,37900000.0,75600000,7200397,Benign
4,500,17,21/02/2018 08:33:11,99743999,5,0,2500,0,500,500,...,8,4000286.0,0.0,4000286,4000286,31900000.0,37900000.0,75600000,7200399,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,55484,6,21/02/2018 02:33:29,1252,5,2,935,274,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048571,57624,6,21/02/2018 02:33:29,19055,5,2,935,341,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048572,57623,6,21/02/2018 02:33:29,36677,5,2,935,341,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048573,57625,6,21/02/2018 02:33:29,1849,5,2,935,341,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048574,58120,6,21/02/2018 02:33:29,20580,5,2,935,299,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [65]:
df_wednesday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [66]:
df_wednesday2["Label"].unique()

array(['Benign', 'DDOS attack-LOIC-UDP', 'DDOS attack-HOIC'], dtype=object)

In [67]:
print(df_wednesday2["Label"].value_counts()[['Benign']].sum())
print(df_wednesday2["Label"].value_counts()[['DDOS attack-LOIC-UDP']].sum())
print(df_wednesday2["Label"].value_counts()[['DDOS attack-HOIC']].sum())

360833
1730
686012

In [68]:
# cut only benign 
df9_benign = df_wednesday2.loc[df_wednesday2['Label'] == 'Benign']
print(df9_benign.shape[0])

# cut only DDOS attack-LOIC-UDP
df9_ddos_loicudp = df_wednesday2.loc[df_wednesday2['Label'] == 'DDOS attack-LOIC-UDP']
print(df9_ddos_loicudp.shape[0])

# cut only DDOS attack-HOIC
df9_ddos_hoic = df_wednesday2.loc[df_wednesday2['Label'] == 'DDOS attack-HOIC']
print(df9_ddos_hoic.shape[0])

1730
686012

In [69]:
# take benign
print(df9_benign.shape[0])

# take 1730 DDOS attack-LOIC-UDP
df9_ddos_loicudp = df9_ddos_loicudp.head(1730)
print(df9_ddos_loicudp.shape[0])

# take 34301 DDOS attack-HOIC
df9_ddos_hoic = df9_ddos_hoic.head(34301)
print(df9_ddos_hoic.shape[0])

1730
34301

#### 3.3 Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

In [70]:
df_wednesday3 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-28-2018.csv', low_memory=False)

In [71]:
df_wednesday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,28/02/2018 08:22:13,94658,6,7,708,3718,387,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,443,6,28/02/2018 08:22:13,206,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,445,6,28/02/2018 08:22:15,165505,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,443,6,28/02/2018 08:22:16,102429,6,7,708,3718,387,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,443,6,28/02/2018 08:22:16,167,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613066,23,6,28/02/2018 11:59:12,3,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
613067,425,6,28/02/2018 10:50:04,2,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
613068,445,6,28/02/2018 12:52:55,732728,2,2,0,0,0,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
613069,23,6,28/02/2018 11:10:50,22,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
613070,443,6,28/02/2018 11:12:18,2,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration

In [72]:
df_wednesday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [73]:
df_wednesday3["Label"].unique()

array(['Benign', 'Infilteration'], dtype=object)

In [74]:
print(df_wednesday3["Label"].value_counts()[['Benign']].sum())
# print(df_wednesday3["Label"].value_counts()[['Label']].sum())
print(df_wednesday3["Label"].value_counts()[['Infilteration']].sum())

544200
68871

In [75]:
df_wednesday3.loc[df_wednesday3["Label"] == "Label"]

Empty DataFrame
Columns: [Dst Port, Protocol, Timestamp, Flow Duration, Tot Fwd Pkts, Tot Bwd Pkts, TotLen Fwd Pkts, TotLen Bwd Pkts, Fwd Pkt Len Max, Fwd Pkt Len Min, Fwd Pkt Len Mean, Fwd Pkt Len Std, Bwd Pkt Len Max, Bwd Pkt Len Min, Bwd Pkt Len Mean, Bwd Pkt Len Std, Flow Byts/s, Flow Pkts/s, Flow IAT Mean, Flow IAT Std, Flow IAT Max, Flow IAT Min, Fwd IAT Tot, Fwd IAT Mean, Fwd IAT Std, Fwd IAT Max, Fwd IAT Min, Bwd IAT Tot, Bwd IAT Mean, Bwd IAT Std, Bwd IAT Max, Bwd IAT Min, Fwd PSH Flags, Bwd PSH Flags, Fwd URG Flags, Bwd URG Flags, Fwd Header Len, Bwd Header Len, Fwd Pkts/s, Bwd Pkts/s, Pkt Len Min, Pkt Len Max, Pkt Len Mean, Pkt Len Std, Pkt Len Var, FIN Flag Cnt, SYN Flag Cnt, RST Flag Cnt, PSH Flag Cnt, ACK Flag Cnt, URG Flag Cnt, CWE Flag Count, ECE Flag Cnt, Down/Up Ratio, Pkt Size Avg, Fwd Seg Size Avg, Bwd Seg Size Avg, Fwd Byts/b Avg, Fwd Pkts/b Avg, Fwd Blk Rate Avg, Bwd Byts/b Avg, Bwd Pkts/b Avg, Bwd Blk Rate Avg, Subflow Fwd Pkts, Subflow Fwd Byts, Subflow Bwd Pkts, Subflow Bwd Byts, Init Fwd Win Byts, Init Bwd Win Byts, Fwd Act Data Pkts, Fwd Seg Size Min, Active Mean, Active Std, Active Max, Active Min, Idle Mean, Idle Std, Idle Max, Idle Min, Label]
Index: []

[0 rows x 80 columns]

In [76]:
# cut only benign 
df10_benign = df_wednesday3.loc[df_wednesday3['Label'] == 'Benign']
print(df10_benign.shape[0])

# cut only Infilteration
df10_infilteration = df_wednesday3.loc[df_wednesday3['Label'] == 'Infilteration']
print(df10_infilteration.shape[0])

68871

In [77]:
# take benign
print(df10_benign.shape[0])

# take 4049 Infilteration
df10_infilteration = df10_infilteration.head(4049)
print(df10_infilteration.shape[0])

4049

### 4- Sum data for dataset for training and make final dataset csv file

In [78]:
# check again number of each attacks in 10 days

# benign - 63489
print("Number of benign in the first day (it must be 63489) : ",df1_benign.shape[0])
print("Number of benign in the 2nd day (it must be 63489) : ",df2_benign.shape[0])
print("Number of benign in the 3rd day (it must be 63489) : ",df3_benign.shape[0])
print("Number of benign in the 4th day (it must be 63489) : ",df4_benign.shape[0])
print("Number of benign in the 5th day (it must be 63489) : ",df5_benign.shape[0])
print("Number of benign in the 6th day (it must be 63489) : ",df6_benign.shape[0])
print("Number of benign in the 7th day (it must be 63489) : ",df7_benign.shape[0])
print("Number of benign in the 8th day (it must be 63489) : ",df8_benign.shape[0])
print("Number of benign in the 9th day (it must be 63489) : ",df9_benign.shape[0])
print("Number of benign in the 10th day (it must be 63489) : ",df10_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 1. Bot - 14310
print("Number of bot in the first day (it must be 14310) : ",df1_bot.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 2. Dos attacks-SlowHTTPTest - 69945 
print("Number of Dos attacks-SlowHTTPTest in the 2nd day (it must be 69945) : ",df2_dos_slowhttptest.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 3. DoS attacks - Hulk - 23334
print("Number of DoS attacks - Hulk in the 2nd day (it must be 23334) : ",df2_dos_hulk.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 4. Brute Force -Web - 362 + 249 = 611
print("Number of Brute Force -Web in the 3rd day (it must be 362) : ",df3_brute_forceweb.shape[0])
print("Number of Brute Force -Web the 7th day (it must be 249) : ",df7_bruteforce_web.shape[0])
df37_bruteforce_web = pd.concat([df3_brute_forceweb, df7_bruteforce_web], axis=0, ignore_index=True)
print("Number of Brute Force -Web in total (it must be 611) : ",df37_bruteforce_web.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 5. Brute Force -XSS - 151 + 79 = 230
print("Number of Brute Force -XSS in the 3rd day (it must be 151) : ",df3_brute_forcexss.shape[0])
print("Number of Brute Force -XSS in the 7th day (it must be 79) : ",df7_bruteforce_xss.shape[0])
df37_bruteforce_xss = pd.concat([df3_brute_forcexss, df7_bruteforce_xss], axis=0, ignore_index=True)
print("Number of Brute Force -XSS in total (it must be 230) : ",df37_bruteforce_xss.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 6. SQL Injection - 53+34=87
print("Number of SQL Injection in the 3rd day (it must be 53) : ",df3_sqlinjection.shape[0])
print("Number of SQL Injection in the 7th day (it must be 34) : ",df7_sql_injection.shape[0])
df37_SQL_injection = pd.concat([df3_sqlinjection, df7_sql_injection], axis=0, ignore_index=True)
print("Number of SQL Injection in total (it must be 87) : ",df37_SQL_injection.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 7. DDoS attacks-LOIC-HTTP - 28810
print("Number of DDoS attacks-LOIC-HTTP in the 4th day (it must be 28810) : ",df4_DDoS_loichttp.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 8. Infilteration - 4049 + 4049
print("Number of Infilteration in the 5th day (it must be 4049) : ",df5_infilteration.shape[0])
print("Number of Infilteration in the 10th day (it must be 4049) : ",df10_infilteration.shape[0])
df510_infilteration = pd.concat([df5_infilteration, df10_infilteration], axis=0, ignore_index=True)
print("Number of infilteration in total (it must be 8098) : ",df510_infilteration.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 9. DoS attacks - GoldenEye - 20754
print("Number of DoS attacks-GoldenEye in the 6th second day (it must be 20754) : ",df6_dos_goldeneye.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 10. DoS attacks-Slowloris - 5495
print("Number of  DoS attacks-Slowloris in the 6th day (it must be 5495) : ",df6_dos_slowloris.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 11. FTP Brute Force - 19336 
print("Number of FTP Brute Force in the 8th day (it must be 19336) : ",df8_ftp_bruteforce.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 12. SSH Brute Force - 9380 
print("Number of SSH Brute Force in the 8th day (it must be 9380) : ",df8_ssh_bruteforce.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 13. DDOS attack-LOIC-UDP - 1730 
print("Number of  DDOS attack-LOIC-UDP in the 9th day (it must be 1730) : ",df9_ddos_loicudp.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 14. DDOS attack-HOIC - 34301
print("Number of DDOS attack-HOIC in the 9th day (it must be 34301) : ",df9_ddos_hoic.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

Number of benign in the first day (it must be 63489) :  63489
-----------------------------------------------------------------------------------------------
Number of bot in the first day (it must be 14310) :  14310
-----------------------------------------------------------------------------------------------

Number of Dos attacks-SlowHTTPTest in the 2nd day (it must be 69945) :  69945
-----------------------------------------------------------------------------------------------
Number of DoS attacks - Hulk in the 2nd day (it must be 23334) :  23334
-----------------------------------------------------------------------------------------------

Number of Brute Force -Web in the 3rd day (it must be 362) :  362
Number of Brute Force -Web the 7th day (it must be 249) :  249
Number of Brute Force -Web in total (it must be 611) :  611
-----------------------------------------------------------------------------------------------
Number of Brute Force -XSS in the 3rd day (it must be 151) :  151
Number of Brute Force -XSS in the 7th day (it must be 79) :  79
Number of Brute Force -XSS in total (it must be 230) :  230
-----------------------------------------------------------------------------------------------
Number of SQL Injection in the 3rd day (it must be 53) :  53
Number of SQL Injection in the 7th day (it must be 34) :  34
Number of SQL Injection in total (it must be 87) :  87
-----------------------------------------------------------------------------------------------

Number of DDoS attacks-LOIC-HTTP in the 4th day (it must be 28810) :  28810
-----------------------------------------------------------------------------------------------

Number of Infilteration in the 5th day (it must be 4049) :  4049
Number of Infilteration in the 10th day (it must be 4049) :  4049
Number of infilteration in total (it must be 8098) :  8098
-----------------------------------------------------------------------------------------------

Number of DoS attacks-GoldenEye in the 6th second day (it must be 20754) :  20754
-----------------------------------------------------------------------------------------------
Number of  DoS attacks-Slowloris in the 6th day (it must be 5495) :  5495
-----------------------------------------------------------------------------------------------

Number of FTP Brute Force in the 8th day (it must be 19336) :  19336
-----------------------------------------------------------------------------------------------
Number of SSH Brute Force in the 8th day (it must be 9380) :  9380
-----------------------------------------------------------------------------------------------

Number of  DDOS attack-LOIC-UDP in the 9th day (it must be 1730) :  1730
-----------------------------------------------------------------------------------------------
Number of DDOS attack-HOIC in the 9th day (it must be 34301) :  34301
-----------------------------------------------------------------------------------------------

In [79]:
df1_benign

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319310,3389,6,02/03/2018 12:43:02,2264122,8,7,1144,1581.0,677,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
319311,53,17,02/03/2018 09:27:46,919,1,1,39,67.0,39,39,...,8,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
319312,3389,6,02/03/2018 12:11:45,21012043,3,4,0,0.0,0,0,...,32,1507358.5,2128278.981,3012279.0,2438.0,8998663.0,4244276.932,12000000.0,5997506.0,Benign
319313,3389,6,02/03/2018 02:03:16,1623433,8,7,1148,1581.0,677,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
319314,3389,6,02/03/2018 03:21:33,2680524,8,7,1128,1581.0,661,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign

In [80]:
df1_bot

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1234,8080,6,02/03/2018 10:17:07,16079,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
1235,8080,6,02/03/2018 10:17:07,577,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
1236,8080,6,02/03/2018 10:17:09,10279,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
1237,8080,6,02/03/2018 10:17:09,457,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
1240,8080,6,02/03/2018 10:17:11,10271,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16001,8080,6,02/03/2018 12:33:15,10230,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
16002,8080,6,02/03/2018 12:33:15,490,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
16004,8080,6,02/03/2018 12:33:17,9761,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
16005,8080,6,02/03/2018 12:33:17,477,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot
16006,8080,6,02/03/2018 12:33:19,9456,3,4,326,129.0,326,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bot

In [81]:
# sum all 10 days data frame to 1 data frame 

df_sum= pd.concat([df1_benign, df1_bot, df2_dos_slowhttptest, df2_dos_hulk, df37_bruteforce_web,\
                  df37_bruteforce_xss, df37_SQL_injection, df4_DDoS_loichttp, \
                   df6_dos_goldeneye,df510_infilteration,\
                  df6_dos_slowloris, df8_ftp_bruteforce, df8_ssh_bruteforce, df9_ddos_loicudp, \
                  df9_ddos_hoic], axis=0, ignore_index=True)
df_sum.shape[0]

299910

In [83]:
df_sum

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299905,80,6,21/02/2018 02:11:55,20071,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299906,80,6,21/02/2018 02:11:55,21703,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299907,80,6,21/02/2018 02:11:55,19183,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299908,80,6,21/02/2018 02:11:55,23522,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299909,80,6,21/02/2018 02:11:55,30294,2,0,0,0,0,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN

In [86]:
df_sum.shape[0]

299910

In [87]:
df_sum.to_csv("processed_first_final_dataset.csv", index=False)

In [ ]:
996077