# Exploring and Clean Data of the CIC-IDS-2018 Dataset
[official dataset link](https://www.unb.ca/cic/datasets/ids-2018.html)


Based on the following exploration; The __"Friday-02-03-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Friday-16-02-2018_TrafficForML_CICFlowMeter.csv"__, __"Friday-02-23-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv"__, __"Thursday-02-15-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Thursday-02-22-2018_TrafficForML_CICFlowMeter.csv"__, __"Tuesday-02-20-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Wednesday-02-14-2018_TrafficForML_CICFlowMeter.csv"__, __"Wednesday-02-21-2018_TrafficForML_CICFlowMeter.csv"__, 
__"Wednesday-02-28-2018_TrafficForML_CICFlowMeter.csv"__ csv files were chosen with the following labels:
* __Benign__ (1,209,156 total instances)
* __Bot__ (286,191 total instances)
* __DoS attacks-SlowHTTPTest__ (139,890 total instances)
* __DoS attacks-Hulk__ (461,912 total instances)
* __Brute Force -Web__ (1,209,156 total instances)
* __Brute Force -XSS__ (286,191 total instances)
* __SQL Injection__ (139,890 total instances)
* __DDoS attacks-LOIC-HTTP__ (461,912 total instances)
* __DoS attacks-GoldenEye__ (1,209,156 total instances)
* __Infilteration__ (286,191 total instances)
* __DoS attacks-Slowloris__ (139,890 total instances)
* __FTP-BruteForce__ (461,912 total instances)
* __SSH-Bruteforce__ (1,209,156 total instances)
* __DDOS attack-LOIC-UDP__ (286,191 total instances)
* __DDOS attack-HOIC__ (139,890 total instances)
* Label (one erroneous row, would need to be removed)

__Reasoning__: The labels are better balanced than the rest of the files. For the purposes of a baseline experiment; it would be satisfactory.

The __Bot__, __DoS attacks-SlowHTTPTest__, __DoS attacks-Hulk__, __Brute Force -Web__, __Brute Force -XSS__, __SQL Injection__, __DDoS attacks-LOIC-HTTP__, __DoS attacks-GoldenEye__, __Infilteration__, __DoS attacks-Slowloris__, __FTP-BruteForce__, __SSH-Bruteforce__, __DDOS attack-LOIC-UDP__, __DDOS attack-HOIC__ labels would be combined into one __"Malicious"__ label for a total of 887,993 __"Malicious"__ instances

The baseline experiment would be a binary classification experiment between __236,421 "Malicious"__ instances vs __63,489 "Benign"__ instances.

### 1- Friday logs

In [72]:
import pandas as pd

#### 1.1- Friday-02-03-2018_TrafficForML_CICFlowMeter.csv

In [73]:
df_friday1 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/03-02-2018.csv')

In [74]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [75]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [76]:
df_friday1["Label"].unique()

array(['Benign', 'Bot'], dtype=object)

In [77]:
print(df_friday1["Label"].value_counts()[['Benign']].sum())
print(df_friday1["Label"].value_counts()[['Bot']].sum())

762384
286191

### 2- Removing row with erroneous 'Label' label

In [78]:
# Remove erroneous 'Label' row
df_friday1.drop(df_friday1.loc[df_friday1["Label"] == "Label"].index, inplace=True)

In [79]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [80]:
df_friday1.replace(to_replace=['Bot'], value="Malicious", inplace=True)

In [81]:
df_friday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [82]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [83]:
print(df_friday1["Label"].value_counts()[['Benign']].sum())
print(df_friday1["Label"].value_counts()[['Malicious']].sum())

762384
286191

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [84]:
df_friday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [85]:
df_friday1["Protocol"].unique()

array([ 6,  0, 17])

In [86]:
df_friday1 = pd.get_dummies(df_friday1, columns=['Protocol'], drop_first=True)
df_friday1

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,443,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,61.444444,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
1,49684,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,19.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
2,443,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,98.727273,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
3,443,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
4,443,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,142.777778,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,103.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
1048571,3389,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,102.857143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
1048572,3389,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,104.214286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
1048573,3389,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,104.214286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0
1048574,3389,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,102.785714,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,1,0

In [87]:
# making Label column the last column again
df_friday1.insert(len(df_friday1.columns)-1, 'Label', df_friday1.pop('Label'))

In [88]:
df_friday1

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,443,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,61.444444,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1,49684,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,19.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
2,443,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,98.727273,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
3,443,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
4,443,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,142.777778,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3389,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,103.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048571,3389,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,102.857143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048572,3389,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,104.214286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048573,3389,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,104.214286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048574,3389,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,102.785714,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [89]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [90]:
df_friday1.drop(columns=columns_to_drop, inplace=True)

In [91]:
df_friday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1,281,2,1,38,0.0,38,0,19.000000,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
3,132,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048571,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048572,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048573,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048574,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign

### 6- Dropping missing or duplicate values

In [92]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [93]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [94]:
df_friday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1,281,2,1,38,0.0,38,0,19.000000,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
3,132,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048571,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048572,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048573,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048574,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign

In [95]:
df_friday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [96]:
df_friday1.drop_duplicates(inplace=True)

In [97]:
df_friday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1,281,2,1,38,0.0,38,0,19.000000,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
3,132,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048571,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048572,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048573,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign
1048574,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [98]:
print(df_friday1["Label"].value_counts()[['Benign']].sum())
print(df_friday1["Label"].value_counts()[['Malicious']].sum())

627628
144535

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [99]:
df_friday1.replace(to_replace="Benign", value=0, inplace=True)
df_friday1.replace(to_replace="Malicious", value=1, inplace=True)

In [100]:
df_friday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1,281,2,1,38,0.0,38,0,19.000000,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
3,132,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048571,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048572,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048573,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048574,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [101]:
print(df_friday1["Label"].value_counts()[[0]].sum())
print(df_friday1["Label"].value_counts()[[1]].sum())

627628
144535

### 9- Saving dataset

In [102]:
df_friday1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 772163 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      772163 non-null  int64
 1   Tot Fwd Pkts       772163 non-null  int64
 2   Tot Bwd Pkts       772163 non-null  int64
 3   TotLen Fwd Pkts    772163 non-null  int64
 4   TotLen Bwd Pkts    772163 non-null  float64
 5   Fwd Pkt Len Max    772163 non-null  int64
 6   Fwd Pkt Len Min    772163 non-null  int64
 7   Fwd Pkt Len Mean   772163 non-null  float64
 8   Fwd Pkt Len Std    772163 non-null  float64
 9   Bwd Pkt Len Max    772163 non-null  int64
 10  Bwd Pkt Len Min    772163 non-null  int64
 11  Bwd Pkt Len Mean   772163 non-null  float64
 12  Bwd Pkt Len Std    772163 non-null  float64
 13  Flow IAT Mean      772163 non-null  float64
 14  Flow IAT Std       772163 non-null  float64
 15  Flow IAT Max       772163 non-null  float64
 16  Flow IAT Min       772163 non-null  float64
 17  Fwd IAT Tot        772163 non-null  float64
 18  Fwd IAT Mean       772163 non-null  float64
 19  Fwd IAT Std        772163 non-null  float64
 20  Fwd IAT Max        772163 non-null  float64
 21  Fwd IAT Min        772163 non-null  float64
 22  Bwd IAT Tot        772163 non-null  float64
 23  Bwd IAT Mean       772163 non-null  float64
 24  Bwd IAT Std        772163 non-null  float64
 25  Bwd IAT Max        772163 non-null  float64
 26  Bwd IAT Min        772163 non-null  float64
 27  Fwd Header Len     772163 non-null  int64
 28  Bwd Header Len     772163 non-null  int64
 29  Fwd Pkts/s         772163 non-null  float64
 30  Bwd Pkts/s         772163 non-null  float64
 31  Pkt Len Min        772163 non-null  int64
 32  Pkt Len Max        772163 non-null  int64
 33  Pkt Len Mean       772163 non-null  float64
 34  Pkt Len Std        772163 non-null  float64
 35  Pkt Len Var        772163 non-null  float64
 36  FIN Flag Cnt       772163 non-null  int64
 37  SYN Flag Cnt       772163 non-null  int64
 38  RST Flag Cnt       772163 non-null  int64
 39  PSH Flag Cnt       772163 non-null  int64
 40  ACK Flag Cnt       772163 non-null  int64
 41  URG Flag Cnt       772163 non-null  int64
 42  CWE Flag Count     772163 non-null  int64
 43  ECE Flag Cnt       772163 non-null  int64
 44  Down/Up Ratio      772163 non-null  int64
 45  Pkt Size Avg       772163 non-null  float64
 46  Fwd Seg Size Avg   772163 non-null  float64
 47  Bwd Seg Size Avg   772163 non-null  float64
 48  Fwd Byts/b Avg     772163 non-null  int64
 49  Fwd Pkts/b Avg     772163 non-null  int64
 50  Fwd Blk Rate Avg   772163 non-null  int64
 51  Bwd Byts/b Avg     772163 non-null  int64
 52  Bwd Pkts/b Avg     772163 non-null  int64
 53  Bwd Blk Rate Avg   772163 non-null  int64
 54  Subflow Fwd Pkts   772163 non-null  int64
 55  Subflow Fwd Byts   772163 non-null  int64
 56  Subflow Bwd Pkts   772163 non-null  int64
 57  Subflow Bwd Byts   772163 non-null  int64
 58  Init Fwd Win Byts  772163 non-null  int64
 59  Init Bwd Win Byts  772163 non-null  int64
 60  Fwd Act Data Pkts  772163 non-null  int64
 61  Fwd Seg Size Min   772163 non-null  int64
 62  Active Mean        772163 non-null  float64
 63  Active Std         772163 non-null  float64
 64  Active Max         772163 non-null  float64
 65  Active Min         772163 non-null  float64
 66  Idle Mean          772163 non-null  float64
 67  Idle Std           772163 non-null  float64
 68  Idle Max           772163 non-null  float64
 69  Idle Min           772163 non-null  float64
 70  Protocol_6         772163 non-null  uint8
 71  Protocol_17        772163 non-null  uint8
 72  Label              772163 non-null  int64
dtypes: float64(35), int64(36), uint8(2)
memory usage: 425.6 MB

In [103]:
print(df_friday1["Label"].value_counts()[[0]].sum())
print(df_friday1["Label"].value_counts()[[1]].sum())

627628
144535

In [104]:
# take dataframe of benign of the first day
df_friday1_benign =  df_friday1[df_friday1["Label"]==0]
df_friday1_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,141385,9,7,553,3773.0,202,0,61.444444,87.534438,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1,281,2,1,38,0.0,38,0,19.000000,26.870058,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2,279824,11,15,1086,10527.0,385,0,98.727273,129.392497,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
3,132,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
4,274016,9,13,1285,6141.0,517,0,142.777778,183.887722,1460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3982183,14,8,1442,1731.0,725,0,103.000000,191.125412,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048571,3802316,14,8,1440,1731.0,725,0,102.857143,191.172841,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048572,4004239,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048573,3998435,14,8,1459,1731.0,741,0,104.214286,195.113450,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1048574,3972651,14,8,1439,1731.0,725,0,102.785714,191.197111,1179,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [105]:
# take datafram of malicious of the first day
df_friday1_malicious = df_friday1[df_friday1["Label"]==1]
df_friday1_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
1234,16079,3,4,326,129.0,326,0,108.666667,188.216188,112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
1235,577,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
1236,10279,3,4,326,129.0,326,0,108.666667,188.216188,112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
1237,457,2,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
1240,10271,3,4,326,129.0,326,0,108.666667,188.216188,112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356594,9487,10,0,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
356709,1030059,4,2,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
356768,1029998,4,2,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
357370,1030017,4,2,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
357420,1030836,4,2,0,0.0,0,0,0.000000,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1

#### 1.2- Friday-16-02-2018_TrafficForML_CICFlowMeter.csv

In [107]:
df_friday2 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-16-2018.csv', low_memory=False)

In [108]:
df_friday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,...,0,0,0,0,0,56300000,138.5929291,56300000,56300000,Benign
1,0,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,...,0,0,0,0,0,56300000,263.7508294,56300000,56300000,Benign
2,35605,6,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,...,20,2624734,0,2624734,2624734,9058214,0,9058214,9058214,Benign
3,0,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,...,0,0,0,0,0,56300000,82.02438662,56300000,56300000,Benign
4,23,6,16/02/2018 08:27:59,20,1,1,0,0,0,0,...,20,0,0,0,0,0,0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048571,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048572,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048573,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048574,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest

In [109]:
df_friday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [110]:
df_friday2["Label"].unique()

array(['Benign', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Hulk', 'Label'],
      dtype=object)

In [111]:
print(df_friday2["Label"].value_counts()[['Benign']].sum())
print(df_friday2["Label"].value_counts()[['DoS attacks-SlowHTTPTest']].sum())
print(df_friday2["Label"].value_counts()[['DoS attacks-Hulk']].sum())
print(df_friday2["Label"].value_counts()[['Label']].sum())

446772
139890
461912
1

### 2- Removing row with erroneous 'Label' label

In [112]:
# Remove erroneous 'Label' row
df_friday2.drop(df_friday2.loc[df_friday2["Label"] == "Label"].index, inplace=True)

In [113]:
df_friday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,...,0,0,0,0,0,56300000,138.5929291,56300000,56300000,Benign
1,0,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,...,0,0,0,0,0,56300000,263.7508294,56300000,56300000,Benign
2,35605,6,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,...,20,2624734,0,2624734,2624734,9058214,0,9058214,9058214,Benign
3,0,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,...,0,0,0,0,0,56300000,82.02438662,56300000,56300000,Benign
4,23,6,16/02/2018 08:27:59,20,1,1,0,0,0,0,...,20,0,0,0,0,0,0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048571,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048572,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048573,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest
1048574,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,DoS attacks-SlowHTTPTest

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [118]:
df_friday2.replace(to_replace=['DoS attacks-SlowHTTPTest'], value="Malicious", inplace=True)
df_friday2.replace(to_replace=['DoS attacks-Hulk'], value="Malicious", inplace=True)

In [119]:
df_friday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,...,0,0,0,0,0,56300000,138.5929291,56300000,56300000,Benign
1,0,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,...,0,0,0,0,0,56300000,263.7508294,56300000,56300000,Benign
2,35605,6,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,...,20,2624734,0,2624734,2624734,9058214,0,9058214,9058214,Benign
3,0,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,...,0,0,0,0,0,56300000,82.02438662,56300000,56300000,Benign
4,23,6,16/02/2018 08:27:59,20,1,1,0,0,0,0,...,20,0,0,0,0,0,0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,Malicious
1048571,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,Malicious
1048572,21,6,16/02/2018 10:36:33,3,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,Malicious
1048573,21,6,16/02/2018 10:36:33,5,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,Malicious
1048574,21,6,16/02/2018 10:36:33,2,1,1,0,0,0,0,...,40,0,0,0,0,0,0,0,0,Malicious

In [120]:
df_friday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [121]:
print(df_friday2["Label"].value_counts()[['Benign']].sum())
print(df_friday2["Label"].value_counts()[['Malicious']].sum())

446772
601802

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [122]:
df_friday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [123]:
df_friday2["Protocol"].unique()

array(['0', '6', '17'], dtype=object)

In [124]:
df_friday2 = pd.get_dummies(df_friday2, columns=['Protocol'], drop_first=True)
df_friday2

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_17,Protocol_6
0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,Benign,0,0
1,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,Benign,0,0
2,35605,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,105.0434783,...,0,2624734,2624734,9058214,0,9058214,9058214,Benign,0,1
3,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,Benign,0,0
4,23,16/02/2018 08:27:59,20,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,Benign,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,Malicious,0,1
1048571,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,Malicious,0,1
1048572,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,Malicious,0,1
1048573,21,16/02/2018 10:36:33,5,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,Malicious,0,1
1048574,21,16/02/2018 10:36:33,2,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,Malicious,0,1

In [125]:
# making Label column the last column again
df_friday2.insert(len(df_friday2.columns)-1, 'Label', df_friday2.pop('Label'))

In [126]:
df_friday2

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,0,0,Benign
1,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,0,0,Benign
2,35605,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,105.0434783,...,0,2624734,2624734,9058214,0,9058214,9058214,0,1,Benign
3,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,0,0,Benign
4,23,16/02/2018 08:27:59,20,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048571,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048572,21,16/02/2018 10:36:33,3,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048573,21,16/02/2018 10:36:33,5,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048574,21,16/02/2018 10:36:33,2,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [127]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [128]:
df_friday2.drop(columns=columns_to_drop, inplace=True)

In [129]:
df_friday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,112640768,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,0,0,Benign
1,112641773,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,0,0,Benign
2,20784143,23,44,2416,1344,240,64,105.0434783,54.5422924,64,...,0,2624734,2624734,9058214,0,9058214,9058214,0,1,Benign
3,112640836,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,0,0,Benign
4,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048571,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048572,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048573,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048574,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious

### 6- Dropping missing or duplicate values

In [130]:
df_friday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [131]:
df_friday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [132]:
df_friday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,112640768,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,0,0,Benign
1,112641773,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,0,0,Benign
2,20784143,23,44,2416,1344,240,64,105.0434783,54.5422924,64,...,0,2624734,2624734,9058214,0,9058214,9058214,0,1,Benign
3,112640836,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,0,0,Benign
4,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048571,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048572,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048573,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious
1048574,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Malicious

In [133]:
df_friday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [134]:
df_friday2.drop_duplicates(inplace=True)

In [135]:
df_friday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,112640768,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,0,0,Benign
1,112641773,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,0,0,Benign
2,20784143,23,44,2416,1344,240,64,105.0434783,54.5422924,64,...,0,2624734,2624734,9058214,0,9058214,9058214,0,1,Benign
3,112640836,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,0,0,Benign
4,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999990,4136655,5,3,935,381,935,0,187,418.1447118,381,...,0,0,0,0,0,0,0,0,1,Benign
999992,4122212,5,3,935,413,935,0,187,418.1447118,413,...,0,0,0,0,0,0,0,0,1,Benign
999994,4122731,5,3,935,335,935,0,187,418.1447118,335,...,0,0,0,0,0,0,0,0,1,Benign
999996,4135673,5,3,935,309,935,0,187,418.1447118,309,...,0,0,0,0,0,0,0,0,1,Benign
999998,5270974,5,4,935,387,935,0,187,418.1447118,387,...,0,0,0,0,0,0,0,0,1,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [136]:
print(df_friday2["Label"].value_counts()[['Benign']].sum())
print(df_friday2["Label"].value_counts()[['Malicious']].sum())

446619
145254

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [137]:
df_friday2.replace(to_replace="Benign", value=0, inplace=True)
df_friday2.replace(to_replace="Malicious", value=1, inplace=True)

In [138]:
df_friday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,112640768,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,0,0,0
1,112641773,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,0,0,0
2,20784143,23,44,2416,1344,240,64,105.0434783,54.5422924,64,...,0,2624734,2624734,9058214,0,9058214,9058214,0,1,0
3,112640836,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,0,0,0
4,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999990,4136655,5,3,935,381,935,0,187,418.1447118,381,...,0,0,0,0,0,0,0,0,1,0
999992,4122212,5,3,935,413,935,0,187,418.1447118,413,...,0,0,0,0,0,0,0,0,1,0
999994,4122731,5,3,935,335,935,0,187,418.1447118,335,...,0,0,0,0,0,0,0,0,1,0
999996,4135673,5,3,935,309,935,0,187,418.1447118,309,...,0,0,0,0,0,0,0,0,1,0
999998,5270974,5,4,935,387,935,0,187,418.1447118,387,...,0,0,0,0,0,0,0,0,1,0

In [139]:
print(df_friday2["Label"].value_counts()[[0]].sum())
print(df_friday2["Label"].value_counts()[[1]].sum())

446619
145254

### 9- Saving dataset

In [140]:
df_friday2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 591873 entries, 0 to 999998
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      591873 non-null  object
 1   Tot Fwd Pkts       591873 non-null  object
 2   Tot Bwd Pkts       591873 non-null  object
 3   TotLen Fwd Pkts    591873 non-null  object
 4   TotLen Bwd Pkts    591873 non-null  object
 5   Fwd Pkt Len Max    591873 non-null  object
 6   Fwd Pkt Len Min    591873 non-null  object
 7   Fwd Pkt Len Mean   591873 non-null  object
 8   Fwd Pkt Len Std    591873 non-null  object
 9   Bwd Pkt Len Max    591873 non-null  object
 10  Bwd Pkt Len Min    591873 non-null  object
 11  Bwd Pkt Len Mean   591873 non-null  object
 12  Bwd Pkt Len Std    591873 non-null  object
 13  Flow IAT Mean      591873 non-null  object
 14  Flow IAT Std       591873 non-null  object
 15  Flow IAT Max       591873 non-null  object
 16  Flow IAT Min       591873 non-null  object
 17  Fwd IAT Tot        591873 non-null  object
 18  Fwd IAT Mean       591873 non-null  object
 19  Fwd IAT Std        591873 non-null  object
 20  Fwd IAT Max        591873 non-null  object
 21  Fwd IAT Min        591873 non-null  object
 22  Bwd IAT Tot        591873 non-null  object
 23  Bwd IAT Mean       591873 non-null  object
 24  Bwd IAT Std        591873 non-null  object
 25  Bwd IAT Max        591873 non-null  object
 26  Bwd IAT Min        591873 non-null  object
 27  Fwd Header Len     591873 non-null  object
 28  Bwd Header Len     591873 non-null  object
 29  Fwd Pkts/s         591873 non-null  object
 30  Bwd Pkts/s         591873 non-null  object
 31  Pkt Len Min        591873 non-null  object
 32  Pkt Len Max        591873 non-null  object
 33  Pkt Len Mean       591873 non-null  object
 34  Pkt Len Std        591873 non-null  object
 35  Pkt Len Var        591873 non-null  object
 36  FIN Flag Cnt       591873 non-null  object
 37  SYN Flag Cnt       591873 non-null  object
 38  RST Flag Cnt       591873 non-null  object
 39  PSH Flag Cnt       591873 non-null  object
 40  ACK Flag Cnt       591873 non-null  object
 41  URG Flag Cnt       591873 non-null  object
 42  CWE Flag Count     591873 non-null  object
 43  ECE Flag Cnt       591873 non-null  object
 44  Down/Up Ratio      591873 non-null  object
 45  Pkt Size Avg       591873 non-null  object
 46  Fwd Seg Size Avg   591873 non-null  object
 47  Bwd Seg Size Avg   591873 non-null  object
 48  Fwd Byts/b Avg     591873 non-null  object
 49  Fwd Pkts/b Avg     591873 non-null  object
 50  Fwd Blk Rate Avg   591873 non-null  object
 51  Bwd Byts/b Avg     591873 non-null  object
 52  Bwd Pkts/b Avg     591873 non-null  object
 53  Bwd Blk Rate Avg   591873 non-null  object
 54  Subflow Fwd Pkts   591873 non-null  object
 55  Subflow Fwd Byts   591873 non-null  object
 56  Subflow Bwd Pkts   591873 non-null  object
 57  Subflow Bwd Byts   591873 non-null  object
 58  Init Fwd Win Byts  591873 non-null  object
 59  Init Bwd Win Byts  591873 non-null  object
 60  Fwd Act Data Pkts  591873 non-null  object
 61  Fwd Seg Size Min   591873 non-null  object
 62  Active Mean        591873 non-null  object
 63  Active Std         591873 non-null  object
 64  Active Max         591873 non-null  object
 65  Active Min         591873 non-null  object
 66  Idle Mean          591873 non-null  object
 67  Idle Std           591873 non-null  object
 68  Idle Max           591873 non-null  object
 69  Idle Min           591873 non-null  object
 70  Protocol_17        591873 non-null  uint8
 71  Protocol_6         591873 non-null  uint8
 72  Label              591873 non-null  int64
dtypes: int64(1), object(70), uint8(2)
memory usage: 326.3+ MB

In [141]:
print(df_friday2["Label"].value_counts()[[0]].sum())
print(df_friday2["Label"].value_counts()[[1]].sum())

446619
145254

In [142]:
# take dataframe of benign of the first day
df_friday2_benign =  df_friday2[df_friday2["Label"]==0]
df_friday2_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
0,112640768,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,138.5929291,56300000,56300000,0,0,0
1,112641773,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,263.7508294,56300000,56300000,0,0,0
2,20784143,23,44,2416,1344,240,64,105.0434783,54.5422924,64,...,0,2624734,2624734,9058214,0,9058214,9058214,0,1,0
3,112640836,3,0,0,0,0,0,0,0,0,...,0,0,0,56300000,82.02438662,56300000,56300000,0,0,0
4,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999990,4136655,5,3,935,381,935,0,187,418.1447118,381,...,0,0,0,0,0,0,0,0,1,0
999992,4122212,5,3,935,413,935,0,187,418.1447118,413,...,0,0,0,0,0,0,0,0,1,0
999994,4122731,5,3,935,335,935,0,187,418.1447118,335,...,0,0,0,0,0,0,0,0,1,0
999996,4135673,5,3,935,309,935,0,187,418.1447118,309,...,0,0,0,0,0,0,0,0,1,0
999998,5270974,5,4,935,387,935,0,187,418.1447118,387,...,0,0,0,0,0,0,0,0,1,0

In [143]:
# take datafram of malicious of the first day
df_friday2_malicious = df_friday2[df_friday2["Label"]==1]
df_friday2_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_17,Protocol_6,Label
97,21,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
98,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
101,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
107,20,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
117,22,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998959,48081,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
998962,50159,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
999282,120976,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
999588,28027,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
999621,27497,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

#### 1.3 Friday-23-02-2018_TrafficForML_CICFlowMeter.csv

In [144]:
df_friday3 = pd.read_csv('/mnt/d/project-chau/dataset/\
cse-cic-ids108/dataset/02-23-2018.csv')

In [145]:
df_friday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,23/02/2018 08:18:29,1532698,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1,500,17,23/02/2018 08:17:45,117573855,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,Benign
2,500,17,23/02/2018 08:17:45,117573848,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,Benign
3,22,6,23/02/2018 08:19:55,1745392,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
4,500,17,23/02/2018 08:18:17,89483474,6,0,3000,0,500,500,...,8,4000364.0,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,54116,6,23/02/2018 09:00:54,85992425,2,0,0,0,0,0,...,20,0.0,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,Benign
1048571,33914,6,23/02/2018 12:31:42,132,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048572,53,17,23/02/2018 12:15:24,79134,1,1,41,98,41,41,...,8,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048573,3389,6,23/02/2018 12:45:39,10053785,11,12,1321,1659,677,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048574,445,6,23/02/2018 09:04:11,566835,6,5,455,338,140,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign

In [146]:
df_friday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [147]:
df_friday3["Label"].unique()

array(['Benign', 'Brute Force -Web', 'Brute Force -XSS', 'SQL Injection'],
      dtype=object)

In [148]:
print(df_friday3["Label"].value_counts()[['Benign']].sum())
print(df_friday3["Label"].value_counts()[['Brute Force -Web']].sum())
print(df_friday3["Label"].value_counts()[['Brute Force -XSS']].sum())
print(df_friday3["Label"].value_counts()[['SQL Injection']].sum())

1048009
362
151
53

### 2- Removing row with erroneous 'Label' label

In [150]:
# Remove erroneous 'Label' row
df_friday3.drop(df_friday3.loc[df_friday3["Label"] == "Label"].index, inplace=True)

In [151]:
df_friday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,23/02/2018 08:18:29,1532698,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1,500,17,23/02/2018 08:17:45,117573855,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,Benign
2,500,17,23/02/2018 08:17:45,117573848,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,Benign
3,22,6,23/02/2018 08:19:55,1745392,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
4,500,17,23/02/2018 08:18:17,89483474,6,0,3000,0,500,500,...,8,4000364.0,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,54116,6,23/02/2018 09:00:54,85992425,2,0,0,0,0,0,...,20,0.0,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,Benign
1048571,33914,6,23/02/2018 12:31:42,132,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048572,53,17,23/02/2018 12:15:24,79134,1,1,41,98,41,41,...,8,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048573,3389,6,23/02/2018 12:45:39,10053785,11,12,1321,1659,677,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048574,445,6,23/02/2018 09:04:11,566835,6,5,455,338,140,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [156]:
df_friday3.replace(to_replace=['Brute Force -Web'], value="Malicious", inplace=True)
df_friday3.replace(to_replace=['Brute Force -XSS'], value="Malicious", inplace=True)
df_friday3.replace(to_replace=['SQL Injection'], value="Malicious", inplace=True)

In [157]:
df_friday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,23/02/2018 08:18:29,1532698,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1,500,17,23/02/2018 08:17:45,117573855,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,Benign
2,500,17,23/02/2018 08:17:45,117573848,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,Benign
3,22,6,23/02/2018 08:19:55,1745392,11,11,1179,1969,648,0,...,32,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
4,500,17,23/02/2018 08:18:17,89483474,6,0,3000,0,500,500,...,8,4000364.0,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,54116,6,23/02/2018 09:00:54,85992425,2,0,0,0,0,0,...,20,0.0,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,Benign
1048571,33914,6,23/02/2018 12:31:42,132,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048572,53,17,23/02/2018 12:15:24,79134,1,1,41,98,41,41,...,8,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048573,3389,6,23/02/2018 12:45:39,10053785,11,12,1321,1659,677,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
1048574,445,6,23/02/2018 09:04:11,566835,6,5,455,338,140,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign

In [158]:
df_friday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [159]:
print(df_friday3["Label"].value_counts()[['Benign']].sum())
print(df_friday3["Label"].value_counts()[['Malicious']].sum())

1048009
566

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [160]:
df_friday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [161]:
df_friday3["Protocol"].unique()

array([ 6, 17,  0])

In [162]:
df_friday3 = pd.get_dummies(df_friday3, columns=['Protocol'], drop_first=True)
df_friday3

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,22,23/02/2018 08:18:29,1532698,11,11,1179,1969,648,0,107.181818,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
1,500,23/02/2018 08:17:45,117573855,3,0,1500,0,500,500,500.000000,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,Benign,0,1
2,500,23/02/2018 08:17:45,117573848,3,0,1500,0,500,500,500.000000,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,Benign,0,1
3,22,23/02/2018 08:19:55,1745392,11,11,1179,1969,648,0,107.181818,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
4,500,23/02/2018 08:18:17,89483474,6,0,3000,0,500,500,500.000000,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,Benign,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,54116,23/02/2018 09:00:54,85992425,2,0,0,0,0,0,0.000000,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,Benign,1,0
1048571,33914,23/02/2018 12:31:42,132,2,0,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
1048572,53,23/02/2018 12:15:24,79134,1,1,41,98,41,41,41.000000,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,0,1
1048573,3389,23/02/2018 12:45:39,10053785,11,12,1321,1659,677,0,120.090909,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
1048574,445,23/02/2018 09:04:11,566835,6,5,455,338,140,0,75.833333,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0

In [163]:
# making Label column the last column again
df_friday3.insert(len(df_friday3.columns)-1, 'Label', df_friday3.pop('Label'))

In [164]:
df_friday3

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,22,23/02/2018 08:18:29,1532698,11,11,1179,1969,648,0,107.181818,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1,500,23/02/2018 08:17:45,117573855,3,0,1500,0,500,500,500.000000,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,0,1,Benign
2,500,23/02/2018 08:17:45,117573848,3,0,1500,0,500,500,500.000000,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,0,1,Benign
3,22,23/02/2018 08:19:55,1745392,11,11,1179,1969,648,0,107.181818,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
4,500,23/02/2018 08:18:17,89483474,6,0,3000,0,500,500,500.000000,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,54116,23/02/2018 09:00:54,85992425,2,0,0,0,0,0,0.000000,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,1,0,Benign
1048571,33914,23/02/2018 12:31:42,132,2,0,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048572,53,23/02/2018 12:15:24,79134,1,1,41,98,41,41,41.000000,...,0.0,0,0,0.0,0.000000e+00,0,0,0,1,Benign
1048573,3389,23/02/2018 12:45:39,10053785,11,12,1321,1659,677,0,120.090909,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048574,445,23/02/2018 09:04:11,566835,6,5,455,338,140,0,75.833333,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [165]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [166]:
df_friday3.drop(columns=columns_to_drop, inplace=True)

In [167]:
df_friday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,1532698,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1,117573855,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,0,1,Benign
2,117573848,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,0,1,Benign
3,1745392,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
4,89483474,6,0,3000,0,500,500,500.000000,0.000000,0,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,85992425,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,1,0,Benign
1048571,132,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048572,79134,1,1,41,98,41,41,41.000000,0.000000,98,...,0.0,0,0,0.0,0.000000e+00,0,0,0,1,Benign
1048573,10053785,11,12,1321,1659,677,0,120.090909,197.116440,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048574,566835,6,5,455,338,140,0,75.833333,62.936211,145,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign

### 6- Dropping missing or duplicate values

In [168]:
df_friday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [169]:
df_friday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [170]:
df_friday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,1532698,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1,117573855,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,0,1,Benign
2,117573848,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,0,1,Benign
3,1745392,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
4,89483474,6,0,3000,0,500,500,500.000000,0.000000,0,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,85992425,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,1,0,Benign
1048571,132,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048572,79134,1,1,41,98,41,41,41.000000,0.000000,98,...,0.0,0,0,0.0,0.000000e+00,0,0,0,1,Benign
1048573,10053785,11,12,1321,1659,677,0,120.090909,197.116440,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048574,566835,6,5,455,338,140,0,75.833333,62.936211,145,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign

In [171]:
df_friday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [172]:
df_friday3.drop_duplicates(inplace=True)

In [173]:
df_friday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,1532698,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1,117573855,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,0,1,Benign
2,117573848,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,0,1,Benign
3,1745392,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
4,89483474,6,0,3000,0,500,500,500.000000,0.000000,0,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,19276110,5,10,286,738,103,0,57.200000,52.485236,409,...,0.0,9667037,9667037,9609073.0,0.000000e+00,9609073,9609073,1,0,Benign
1048570,85992425,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,1,0,Benign
1048572,79134,1,1,41,98,41,41,41.000000,0.000000,98,...,0.0,0,0,0.0,0.000000e+00,0,0,0,1,Benign
1048573,10053785,11,12,1321,1659,677,0,120.090909,197.116440,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048574,566835,6,5,455,338,140,0,75.833333,62.936211,145,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [174]:
print(df_friday3["Label"].value_counts()[['Benign']].sum())
print(df_friday3["Label"].value_counts()[['Malicious']].sum())

829557
541

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [175]:
df_friday3.replace(to_replace="Benign", value=0, inplace=True)
df_friday3.replace(to_replace="Malicious", value=1, inplace=True)

In [176]:
df_friday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,1532698,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
1,117573855,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,0,1,0
2,117573848,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,0,1,0
3,1745392,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
4,89483474,6,0,3000,0,500,500,500.000000,0.000000,0,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,19276110,5,10,286,738,103,0,57.200000,52.485236,409,...,0.0,9667037,9667037,9609073.0,0.000000e+00,9609073,9609073,1,0,0
1048570,85992425,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,1,0,0
1048572,79134,1,1,41,98,41,41,41.000000,0.000000,98,...,0.0,0,0,0.0,0.000000e+00,0,0,0,1,0
1048573,10053785,11,12,1321,1659,677,0,120.090909,197.116440,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
1048574,566835,6,5,455,338,140,0,75.833333,62.936211,145,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0

In [177]:
print(df_friday3["Label"].value_counts()[[0]].sum())
print(df_friday3["Label"].value_counts()[[1]].sum())

829557
541

### 9- Saving dataset

In [178]:
df_friday3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830098 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      830098 non-null  int64
 1   Tot Fwd Pkts       830098 non-null  int64
 2   Tot Bwd Pkts       830098 non-null  int64
 3   TotLen Fwd Pkts    830098 non-null  int64
 4   TotLen Bwd Pkts    830098 non-null  int64
 5   Fwd Pkt Len Max    830098 non-null  int64
 6   Fwd Pkt Len Min    830098 non-null  int64
 7   Fwd Pkt Len Mean   830098 non-null  float64
 8   Fwd Pkt Len Std    830098 non-null  float64
 9   Bwd Pkt Len Max    830098 non-null  int64
 10  Bwd Pkt Len Min    830098 non-null  int64
 11  Bwd Pkt Len Mean   830098 non-null  float64
 12  Bwd Pkt Len Std    830098 non-null  float64
 13  Flow IAT Mean      830098 non-null  float64
 14  Flow IAT Std       830098 non-null  float64
 15  Flow IAT Max       830098 non-null  int64
 16  Flow IAT Min       830098 non-null  int64
 17  Fwd IAT Tot        830098 non-null  int64
 18  Fwd IAT Mean       830098 non-null  float64
 19  Fwd IAT Std        830098 non-null  float64
 20  Fwd IAT Max        830098 non-null  int64
 21  Fwd IAT Min        830098 non-null  int64
 22  Bwd IAT Tot        830098 non-null  int64
 23  Bwd IAT Mean       830098 non-null  float64
 24  Bwd IAT Std        830098 non-null  float64
 25  Bwd IAT Max        830098 non-null  int64
 26  Bwd IAT Min        830098 non-null  int64
 27  Fwd Header Len     830098 non-null  int64
 28  Bwd Header Len     830098 non-null  int64
 29  Fwd Pkts/s         830098 non-null  float64
 30  Bwd Pkts/s         830098 non-null  float64
 31  Pkt Len Min        830098 non-null  int64
 32  Pkt Len Max        830098 non-null  int64
 33  Pkt Len Mean       830098 non-null  float64
 34  Pkt Len Std        830098 non-null  float64
 35  Pkt Len Var        830098 non-null  float64
 36  FIN Flag Cnt       830098 non-null  int64
 37  SYN Flag Cnt       830098 non-null  int64
 38  RST Flag Cnt       830098 non-null  int64
 39  PSH Flag Cnt       830098 non-null  int64
 40  ACK Flag Cnt       830098 non-null  int64
 41  URG Flag Cnt       830098 non-null  int64
 42  CWE Flag Count     830098 non-null  int64
 43  ECE Flag Cnt       830098 non-null  int64
 44  Down/Up Ratio      830098 non-null  int64
 45  Pkt Size Avg       830098 non-null  float64
 46  Fwd Seg Size Avg   830098 non-null  float64
 47  Bwd Seg Size Avg   830098 non-null  float64
 48  Fwd Byts/b Avg     830098 non-null  int64
 49  Fwd Pkts/b Avg     830098 non-null  int64
 50  Fwd Blk Rate Avg   830098 non-null  int64
 51  Bwd Byts/b Avg     830098 non-null  int64
 52  Bwd Pkts/b Avg     830098 non-null  int64
 53  Bwd Blk Rate Avg   830098 non-null  int64
 54  Subflow Fwd Pkts   830098 non-null  int64
 55  Subflow Fwd Byts   830098 non-null  int64
 56  Subflow Bwd Pkts   830098 non-null  int64
 57  Subflow Bwd Byts   830098 non-null  int64
 58  Init Fwd Win Byts  830098 non-null  int64
 59  Init Bwd Win Byts  830098 non-null  int64
 60  Fwd Act Data Pkts  830098 non-null  int64
 61  Fwd Seg Size Min   830098 non-null  int64
 62  Active Mean        830098 non-null  float64
 63  Active Std         830098 non-null  float64
 64  Active Max         830098 non-null  int64
 65  Active Min         830098 non-null  int64
 66  Idle Mean          830098 non-null  float64
 67  Idle Std           830098 non-null  float64
 68  Idle Max           830098 non-null  int64
 69  Idle Min           830098 non-null  int64
 70  Protocol_6         830098 non-null  uint8
 71  Protocol_17        830098 non-null  uint8
 72  Label              830098 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 457.6 MB

In [179]:
print(df_friday3["Label"].value_counts()[[0]].sum())
print(df_friday3["Label"].value_counts()[[1]].sum())

829557
541

In [180]:
# take dataframe of benign of the first day
df_friday3_benign =  df_friday3[df_friday3["Label"]==0]
df_friday3_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,1532698,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
1,117573855,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786927.5,2.375324e+07,75583006,41990849,0,1,0
2,117573848,3,0,1500,0,500,500,500.000000,0.000000,0,...,0.0,0,0,58786924.0,2.375325e+07,75583007,41990841,0,1,0
3,1745392,11,11,1179,1969,648,0,107.181818,196.245162,976,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
4,89483474,6,0,3000,0,500,500,500.000000,0.000000,0,...,0.0,4000364,4000364,21370777.5,1.528092e+07,41989576,7200485,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,19276110,5,10,286,738,103,0,57.200000,52.485236,409,...,0.0,9667037,9667037,9609073.0,0.000000e+00,9609073,9609073,1,0,0
1048570,85992425,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,85992425.0,0.000000e+00,85992425,85992425,1,0,0
1048572,79134,1,1,41,98,41,41,41.000000,0.000000,98,...,0.0,0,0,0.0,0.000000e+00,0,0,0,1,0
1048573,10053785,11,12,1321,1659,677,0,120.090909,197.116440,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
1048574,566835,6,5,455,338,140,0,75.833333,62.936211,145,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0

In [181]:
# take datafram of malicious of the first day
df_friday3_malicious = df_friday3[df_friday3["Label"]==1]
df_friday3_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
339,5821967,3,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
340,55332482,154,107,54442,80771,646,0,353.519481,270.784993,2920,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
341,177,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
342,112640956,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56320478.00,5.374012e+01,56320516,56320440,0,0,1
343,89479476,6,0,3000,0,500,500,500.000000,0.000000,0,...,0.0,4000257,4000257,21369804.75,1.528101e+07,41990219,7200399,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,46,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
1998,277,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
2115,331,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
2216,313,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1
2401,190,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.00,0.000000e+00,0,0,1,0,1

### 2- Thursday logs

#### 2.1 Thursday-20-02-2018_TrafficForML_CICFlowMeter.csv

In [2]:
import pandas as pd

In [3]:
df_thursday1 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-20-2018.csv', low_memory=False)

In [4]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,22,6,20/02/2018 08:34:07,888751,11,11,...,32,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:33:22,112642816,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:36:11,112642712,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:39:00,112642648,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:41:49,112642702,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,443,6,20/02/2018 01:57:49,5129181,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,443,6,20/02/2018 01:57:49,5129544,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,443,6,20/02/2018 01:57:49,5130113,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,51849,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,51848,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign

In [5]:
df_thursday1.columns

Index(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [6]:
df_thursday1["Label"].unique()

array(['Benign', 'DDoS attacks-LOIC-HTTP'], dtype=object)

In [7]:
print(df_thursday1["Label"].value_counts()[['Benign']].sum())
print(df_thursday1["Label"].value_counts()[['DDoS attacks-LOIC-HTTP']].sum())

468277
576191

### 2- Removing row with erroneous 'Label' label

In [8]:
# Remove erroneous 'Label' row
df_thursday1.drop(df_thursday1.loc[df_thursday1["Label"] == "Label"].index, inplace=True)

In [9]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,22,6,20/02/2018 08:34:07,888751,11,11,...,32,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:33:22,112642816,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:36:11,112642712,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:39:00,112642648,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:41:49,112642702,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,443,6,20/02/2018 01:57:49,5129181,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,443,6,20/02/2018 01:57:49,5129544,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,443,6,20/02/2018 01:57:49,5130113,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,51849,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,51848,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [11]:
df_thursday1.replace(to_replace=['DDoS attacks-LOIC-HTTP'], value="Malicious", inplace=True)

In [12]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,22,6,20/02/2018 08:34:07,888751,11,11,...,32,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:33:22,112642816,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:36:11,112642712,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:39:00,112642648,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,0,20/02/2018 08:41:49,112642702,3,0,...,0,0.0,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,443,6,20/02/2018 01:57:49,5129181,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,443,6,20/02/2018 01:57:49,5129544,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,443,6,20/02/2018 01:57:49,5130113,9,7,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,51849,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,51848,6,20/02/2018 01:57:54,0,2,0,...,20,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign

In [13]:
df_thursday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [14]:
print(df_thursday1["Label"].value_counts()[['Benign']].sum())
print(df_thursday1["Label"].value_counts()[['Malicious']].sum())

468277
576191

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [15]:
df_thursday1.columns

Index(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [16]:
df_thursday1["Protocol"].unique()

array([ 6,  0, 17])

In [17]:
df_thursday1 = pd.get_dummies(df_thursday1, columns=['Protocol'], drop_first=True)
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,22,20/02/2018 08:34:07,888751,11,11,1249,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign,1,0
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:33:22,112642816,3,0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign,0,0
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:36:11,112642712,3,0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,Benign,0,0
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:39:00,112642648,3,0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign,0,0
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:41:49,112642702,3,0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,Benign,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,443,20/02/2018 01:57:49,5129181,9,7,597,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign,1,0
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,443,20/02/2018 01:57:49,5129544,9,7,597,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign,1,0
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,443,20/02/2018 01:57:49,5130113,9,7,597,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign,1,0
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,51849,20/02/2018 01:57:54,0,2,0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign,1,0
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,51848,20/02/2018 01:57:54,0,2,0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign,1,0

In [18]:
# making Label column the last column again
df_thursday1.insert(len(df_thursday1.columns)-1, 'Label', df_thursday1.pop('Label'))

In [19]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,22,20/02/2018 08:34:07,888751,11,11,1249,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:33:22,112642816,3,0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,0,0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:36:11,112642712,3,0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,0,0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:39:00,112642648,3,0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,0,0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,0,20/02/2018 08:41:49,112642702,3,0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,443,20/02/2018 01:57:49,5129181,9,7,597,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,443,20/02/2018 01:57:49,5129544,9,7,597,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,443,20/02/2018 01:57:49,5130113,9,7,597,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,51849,20/02/2018 01:57:54,0,2,0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,51848,20/02/2018 01:57:54,0,2,0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [20]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [21]:
df_thursday1.drop(columns=columns_to_drop, inplace=True)

In [22]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,888751,11,11,1249,1969.0,736,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642816,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,0,0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642712,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,0,0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642648,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,0,0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642702,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,5129181,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,5129544,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,5130113,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign

### 6- Dropping missing or duplicate values

In [23]:
df_thursday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [24]:
df_thursday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [25]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,888751,11,11,1249,1969.0,736,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642816,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,0,0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642712,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,0,0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642648,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,0,0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642702,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,5129181,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,5129544,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,5130113,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign

In [26]:
df_thursday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [27]:
df_thursday1.drop_duplicates(inplace=True)

In [28]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,888751,11,11,1249,1969.0,736,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642816,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,0,0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642712,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,0,0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642648,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,0,0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642702,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,5129181,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,5129544,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,5130113,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [29]:
print(df_thursday1["Label"].value_counts()[['Benign']].sum())
print(df_thursday1["Label"].value_counts()[['Malicious']].sum())

468196
576191

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [30]:
df_thursday1.replace(to_replace="Benign", value=0, inplace=True)
df_thursday1.replace(to_replace="Malicious", value=1, inplace=True)

In [31]:
df_thursday1

,Flow ID,Src IP,Src Port,Dst IP,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,888751,11,11,1249,1969.0,736,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642816,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,0,0,0
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642712,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,0,0,0
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642648,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,0,0,0
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642702,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,5129181,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,5129544,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,5130113,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0

In [32]:
print(df_thursday1["Label"].value_counts()[[0]].sum())
print(df_thursday1["Label"].value_counts()[[1]].sum())

468196
576191

### 9- Saving dataset

In [33]:
df_thursday1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1044387 entries, 0 to 1044467
Data columns (total 77 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Flow ID            1044387 non-null  object
 1   Src IP             1044387 non-null  object
 2   Src Port           1044387 non-null  int64
 3   Dst IP             1044387 non-null  object
 4   Flow Duration      1044387 non-null  int64
 5   Tot Fwd Pkts       1044387 non-null  int64
 6   Tot Bwd Pkts       1044387 non-null  int64
 7   TotLen Fwd Pkts    1044387 non-null  int64
 8   TotLen Bwd Pkts    1044387 non-null  float64
 9   Fwd Pkt Len Max    1044387 non-null  int64
 10  Fwd Pkt Len Min    1044387 non-null  int64
 11  Fwd Pkt Len Mean   1044387 non-null  float64
 12  Fwd Pkt Len Std    1044387 non-null  float64
 13  Bwd Pkt Len Max    1044387 non-null  int64
 14  Bwd Pkt Len Min    1044387 non-null  int64
 15  Bwd Pkt Len Mean   1044387 non-null  float64
 16  Bwd Pkt Len Std    1044387 non-null  float64
 17  Flow IAT Mean      1044387 non-null  float64
 18  Flow IAT Std       1044387 non-null  float64
 19  Flow IAT Max       1044387 non-null  float64
 20  Flow IAT Min       1044387 non-null  float64
 21  Fwd IAT Tot        1044387 non-null  float64
 22  Fwd IAT Mean       1044387 non-null  float64
 23  Fwd IAT Std        1044387 non-null  float64
 24  Fwd IAT Max        1044387 non-null  float64
 25  Fwd IAT Min        1044387 non-null  float64
 26  Bwd IAT Tot        1044387 non-null  float64
 27  Bwd IAT Mean       1044387 non-null  float64
 28  Bwd IAT Std        1044387 non-null  float64
 29  Bwd IAT Max        1044387 non-null  float64
 30  Bwd IAT Min        1044387 non-null  float64
 31  Fwd Header Len     1044387 non-null  int64
 32  Bwd Header Len     1044387 non-null  int64
 33  Fwd Pkts/s         1044387 non-null  float64
 34  Bwd Pkts/s         1044387 non-null  float64
 35  Pkt Len Min        1044387 non-null  int64
 36  Pkt Len Max        1044387 non-null  int64
 37  Pkt Len Mean       1044387 non-null  float64
 38  Pkt Len Std        1044387 non-null  float64
 39  Pkt Len Var        1044387 non-null  float64
 40  FIN Flag Cnt       1044387 non-null  int64
 41  SYN Flag Cnt       1044387 non-null  int64
 42  RST Flag Cnt       1044387 non-null  int64
 43  PSH Flag Cnt       1044387 non-null  int64
 44  ACK Flag Cnt       1044387 non-null  int64
 45  URG Flag Cnt       1044387 non-null  int64
 46  CWE Flag Count     1044387 non-null  int64
 47  ECE Flag Cnt       1044387 non-null  int64
 48  Down/Up Ratio      1044387 non-null  int64
 49  Pkt Size Avg       1044387 non-null  float64
 50  Fwd Seg Size Avg   1044387 non-null  float64
 51  Bwd Seg Size Avg   1044387 non-null  float64
 52  Fwd Byts/b Avg     1044387 non-null  int64
 53  Fwd Pkts/b Avg     1044387 non-null  int64
 54  Fwd Blk Rate Avg   1044387 non-null  int64
 55  Bwd Byts/b Avg     1044387 non-null  int64
 56  Bwd Pkts/b Avg     1044387 non-null  int64
 57  Bwd Blk Rate Avg   1044387 non-null  int64
 58  Subflow Fwd Pkts   1044387 non-null  int64
 59  Subflow Fwd Byts   1044387 non-null  int64
 60  Subflow Bwd Pkts   1044387 non-null  int64
 61  Subflow Bwd Byts   1044387 non-null  int64
 62  Init Fwd Win Byts  1044387 non-null  int64
 63  Init Bwd Win Byts  1044387 non-null  int64
 64  Fwd Act Data Pkts  1044387 non-null  int64
 65  Fwd Seg Size Min   1044387 non-null  int64
 66  Active Mean        1044387 non-null  float64
 67  Active Std         1044387 non-null  float64
 68  Active Max         1044387 non-null  float64
 69  Active Min         1044387 non-null  float64
 70  Idle Mean          1044387 non-null  float64
 71  Idle Std           1044387 non-null  float64
 72  Idle Max           1044387 non-null  float64
 73  Idle Min           1044387 non-null  float64
 74  Protocol_6         1044387 non-null  uint8
 75  Protocol_17        1044387 non-null  uint8
 76  Label              1044387 non-null  int64
dtypes: float64(35), int64(37), object(3), uint8(2)
memory usage: 607.6+ MB

In [34]:
print(df_thursday1["Label"].value_counts()[[0]].sum())
print(df_thursday1["Label"].value_counts()[[1]].sum())

468196
576191

In [35]:
# take dataframe of benign of the first day
df_friday4_benign =  df_thursday1[df_thursday1["Label"]==0]
df_friday4_benign

,Flow ID,Src IP,Src Port,Dst IP,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498,172.31.69.25,888751,11,11,1249,1969.0,736,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642816,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,0,0,0
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642712,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,0,0,0
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642648,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,0,0,0
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0,8.0.6.4,112642702,3,0,0,0.0,0,...,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044463,172.31.65.29-23.99.24.158-51849-443-6,172.31.65.29,51849,23.99.24.158,5129181,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044464,172.31.65.29-23.99.24.158-51848-443-6,172.31.65.29,51848,23.99.24.158,5129544,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044465,172.31.65.29-23.99.24.158-51846-443-6,172.31.65.29,51846,23.99.24.158,5130113,9,7,597,4752.0,342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044466,172.31.65.29-23.99.24.158-51849-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0
1044467,172.31.65.29-23.99.24.158-51848-443-6,23.99.24.158,443,172.31.65.29,0,2,0,53,0.0,53,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,1,0,0

In [36]:
# take datafram of malicious of the first day
df_friday4_malicious = df_thursday1[df_thursday1["Label"]==1]
df_friday4_malicious

,Flow ID,Src IP,Src Port,Dst IP,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
38,172.31.69.25-52.14.136.135-80-50819-6,52.14.136.135,50819,172.31.69.25,3904,3,4,20,964.0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
39,172.31.69.25-52.14.136.135-80-50820-6,52.14.136.135,50820,172.31.69.25,762,3,4,20,964.0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
40,172.31.69.25-52.14.136.135-80-50821-6,52.14.136.135,50821,172.31.69.25,726,3,4,20,964.0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
41,172.31.69.25-52.14.136.135-80-50822-6,52.14.136.135,50822,172.31.69.25,556,3,4,20,964.0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
42,172.31.69.25-52.14.136.135-80-50823-6,52.14.136.135,50823,172.31.69.25,916,3,4,20,964.0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576224,172.31.69.25-18.218.11.51-80-58017-6,18.218.11.51,58017,172.31.69.25,25558275,2,0,0,0.0,0,...,0.0,0.0,0.0,25600000.0,0.0,25600000.0,25600000.0,1,0,1
576225,172.31.69.25-52.14.136.135-80-51302-6,52.14.136.135,51302,172.31.69.25,33476462,2,0,0,0.0,0,...,0.0,0.0,0.0,33500000.0,0.0,33500000.0,33500000.0,1,0,1
576226,172.31.69.25-18.218.115.60-80-53361-6,18.218.115.60,53361,172.31.69.25,26767798,2,0,0,0.0,0,...,0.0,0.0,0.0,26800000.0,0.0,26800000.0,26800000.0,1,0,1
576227,172.31.69.25-18.216.200.189-80-59770-6,18.216.200.189,59770,172.31.69.25,32245197,2,0,0,0.0,0,...,0.0,0.0,0.0,32200000.0,0.0,32200000.0,32200000.0,1,0,1
576228,172.31.69.25-18.219.9.1-80-62070-6,18.219.9.1,62070,172.31.69.25,18028704,2,0,0,0.0,0,...,0.0,0.0,0.0,18000000.0,0.0,18000000.0,18000000.0,1,0,1

#### 2.2 Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv

In [37]:
import pandas as pd

In [38]:
df_thursday2 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/03-01-2018.csv')

In [39]:
df_thursday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,1/3/2018 8:17,115307855,5,0,0,0,0,0,...,0,1812348.0,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,Benign
1,0,0,1/3/2018 8:20,60997457,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
2,67,17,1/3/2018 8:17,61149019,5,0,1500,0,300,300,...,8,3530939.0,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,Benign
3,0,0,1/3/2018 8:22,60997555,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
4,0,0,1/3/2018 8:24,61997503,3,0,0,0,0,0,...,0,999909.0,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,0,0,1/3/2018 12:59,118494070,31,0,0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331096,2634,6,1/3/2018 12:59,114340,2,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331097,3389,6,1/3/2018 12:59,1404866,8,7,1132,1581,661,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331098,3389,6,1/3/2018 12:59,3966663,14,7,1386,392,680,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331099,53092,6,1/3/2018 12:59,86637706,2,0,0,0,0,0,...,20,0.0,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,Benign

In [40]:
df_thursday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [41]:
df_thursday2["Label"].unique()

array(['Benign', 'Infilteration'], dtype=object)

In [42]:
print(df_thursday2["Label"].value_counts()[['Benign']].sum())
# print(df_thursday2["Label"].value_counts()[['Label']].sum())
print(df_thursday2["Label"].value_counts()[['Infilteration']].sum())

238037
93063

In [43]:
df_thursday2.loc[df_thursday2["Label"] == "Label"]

Empty DataFrame
Columns: [Dst Port, Protocol, Timestamp, Flow Duration, Tot Fwd Pkts, Tot Bwd Pkts, TotLen Fwd Pkts, TotLen Bwd Pkts, Fwd Pkt Len Max, Fwd Pkt Len Min, Fwd Pkt Len Mean, Fwd Pkt Len Std, Bwd Pkt Len Max, Bwd Pkt Len Min, Bwd Pkt Len Mean, Bwd Pkt Len Std, Flow Byts/s, Flow Pkts/s, Flow IAT Mean, Flow IAT Std, Flow IAT Max, Flow IAT Min, Fwd IAT Tot, Fwd IAT Mean, Fwd IAT Std, Fwd IAT Max, Fwd IAT Min, Bwd IAT Tot, Bwd IAT Mean, Bwd IAT Std, Bwd IAT Max, Bwd IAT Min, Fwd PSH Flags, Bwd PSH Flags, Fwd URG Flags, Bwd URG Flags, Fwd Header Len, Bwd Header Len, Fwd Pkts/s, Bwd Pkts/s, Pkt Len Min, Pkt Len Max, Pkt Len Mean, Pkt Len Std, Pkt Len Var, FIN Flag Cnt, SYN Flag Cnt, RST Flag Cnt, PSH Flag Cnt, ACK Flag Cnt, URG Flag Cnt, CWE Flag Count, ECE Flag Cnt, Down/Up Ratio, Pkt Size Avg, Fwd Seg Size Avg, Bwd Seg Size Avg, Fwd Byts/b Avg, Fwd Pkts/b Avg, Fwd Blk Rate Avg, Bwd Byts/b Avg, Bwd Pkts/b Avg, Bwd Blk Rate Avg, Subflow Fwd Pkts, Subflow Fwd Byts, Subflow Bwd Pkts, Subflow Bwd Byts, Init Fwd Win Byts, Init Bwd Win Byts, Fwd Act Data Pkts, Fwd Seg Size Min, Active Mean, Active Std, Active Max, Active Min, Idle Mean, Idle Std, Idle Max, Idle Min, Label]
Index: []

[0 rows x 80 columns]

### 2- Removing row with erroneous 'Label' label

In [45]:
# Remove erroneous 'Label' row
df_thursday2.drop(df_thursday2.loc[df_thursday1["Label"] == "Label"].index, inplace=True)

In [46]:
df_thursday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,1/3/2018 8:17,115307855,5,0,0,0,0,0,...,0,1812348.0,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,Benign
1,0,0,1/3/2018 8:20,60997457,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
2,67,17,1/3/2018 8:17,61149019,5,0,1500,0,300,300,...,8,3530939.0,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,Benign
3,0,0,1/3/2018 8:22,60997555,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
4,0,0,1/3/2018 8:24,61997503,3,0,0,0,0,0,...,0,999909.0,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,0,0,1/3/2018 12:59,118494070,31,0,0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331096,2634,6,1/3/2018 12:59,114340,2,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331097,3389,6,1/3/2018 12:59,1404866,8,7,1132,1581,661,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331098,3389,6,1/3/2018 12:59,3966663,14,7,1386,392,680,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331099,53092,6,1/3/2018 12:59,86637706,2,0,0,0,0,0,...,20,0.0,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [47]:
df_thursday2.replace(to_replace=['Infilteration'], value="Malicious", inplace=True)

In [48]:
df_thursday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,1/3/2018 8:17,115307855,5,0,0,0,0,0,...,0,1812348.0,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,Benign
1,0,0,1/3/2018 8:20,60997457,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
2,67,17,1/3/2018 8:17,61149019,5,0,1500,0,300,300,...,8,3530939.0,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,Benign
3,0,0,1/3/2018 8:22,60997555,2,0,0,0,0,0,...,0,0.0,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign
4,0,0,1/3/2018 8:24,61997503,3,0,0,0,0,0,...,0,999909.0,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,0,0,1/3/2018 12:59,118494070,31,0,0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331096,2634,6,1/3/2018 12:59,114340,2,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331097,3389,6,1/3/2018 12:59,1404866,8,7,1132,1581,661,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331098,3389,6,1/3/2018 12:59,3966663,14,7,1386,392,680,0,...,20,0.0,0.0,0,0,0.0,0.000000e+00,0,0,Benign
331099,53092,6,1/3/2018 12:59,86637706,2,0,0,0,0,0,...,20,0.0,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,Benign

In [49]:
df_thursday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [50]:
print(df_thursday2["Label"].value_counts()[['Benign']].sum())
print(df_thursday2["Label"].value_counts()[['Malicious']].sum())

238037
93063

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [51]:
df_thursday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [52]:
df_thursday2["Protocol"].unique()

array([ 0, 17,  6])

In [53]:
df_thursday2 = pd.get_dummies(df_thursday2, columns=['Protocol'], drop_first=True)
df_thursday2

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,0,1/3/2018 8:17,115307855,5,0,0,0,0,0,0.0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,Benign,0,0
1,0,1/3/2018 8:20,60997457,2,0,0,0,0,0,0.0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign,0,0
2,67,1/3/2018 8:17,61149019,5,0,1500,0,300,300,300.0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,Benign,0,1
3,0,1/3/2018 8:22,60997555,2,0,0,0,0,0,0.0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,Benign,0,0
4,0,1/3/2018 8:24,61997503,3,0,0,0,0,0,0.0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,Benign,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,0,1/3/2018 12:59,118494070,31,0,0,0,0,0,0.0,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,0,0
331096,2634,1/3/2018 12:59,114340,2,1,0,0,0,0,0.0,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
331097,3389,1/3/2018 12:59,1404866,8,7,1132,1581,661,0,141.5,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
331098,3389,1/3/2018 12:59,3966663,14,7,1386,392,680,0,99.0,...,0.0,0,0,0.0,0.000000e+00,0,0,Benign,1,0
331099,53092,1/3/2018 12:59,86637706,2,0,0,0,0,0,0.0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,Benign,1,0

In [54]:
# making Label column the last column again
df_thursday2.insert(len(df_thursday2.columns)-1, 'Label', df_thursday2.pop('Label'))

In [55]:
df_thursday2

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,0,1/3/2018 8:17,115307855,5,0,0,0,0,0,0.0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,0,0,Benign
1,0,1/3/2018 8:20,60997457,2,0,0,0,0,0,0.0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
2,67,1/3/2018 8:17,61149019,5,0,1500,0,300,300,300.0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,0,1,Benign
3,0,1/3/2018 8:22,60997555,2,0,0,0,0,0,0.0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
4,0,1/3/2018 8:24,61997503,3,0,0,0,0,0,0.0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,0,1/3/2018 12:59,118494070,31,0,0,0,0,0,0.0,...,0.0,0,0,0.0,0.000000e+00,0,0,0,0,Benign
331096,2634,1/3/2018 12:59,114340,2,1,0,0,0,0,0.0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331097,3389,1/3/2018 12:59,1404866,8,7,1132,1581,661,0,141.5,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331098,3389,1/3/2018 12:59,3966663,14,7,1386,392,680,0,99.0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331099,53092,1/3/2018 12:59,86637706,2,0,0,0,0,0,0.0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [56]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [57]:
df_thursday2.drop(columns=columns_to_drop, inplace=True)

In [58]:
df_thursday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,115307855,5,0,0,0,0,0,0.0,0.000000,0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,0,0,Benign
1,60997457,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
2,61149019,5,0,1500,0,300,300,300.0,0.000000,0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,0,1,Benign
3,60997555,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
4,61997503,3,0,0,0,0,0,0.0,0.000000,0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,118494070,31,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,0,0,Benign
331096,114340,2,1,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331097,1404866,8,7,1132,1581,661,0,141.5,222.792023,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331098,3966663,14,7,1386,392,680,0,99.0,189.204814,291,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331099,86637706,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,1,0,Benign

### 6- Dropping missing or duplicate values

In [59]:
df_thursday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [60]:
df_thursday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [61]:
df_thursday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,115307855,5,0,0,0,0,0,0.0,0.000000,0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,0,0,Benign
1,60997457,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
2,61149019,5,0,1500,0,300,300,300.0,0.000000,0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,0,1,Benign
3,60997555,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
4,61997503,3,0,0,0,0,0,0.0,0.000000,0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,118494070,31,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,0,0,Benign
331096,114340,2,1,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331097,1404866,8,7,1132,1581,661,0,141.5,222.792023,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331098,3966663,14,7,1386,392,680,0,99.0,189.204814,291,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331099,86637706,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,1,0,Benign

In [62]:
df_thursday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [63]:
df_thursday2.drop_duplicates(inplace=True)

In [64]:
df_thursday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,115307855,5,0,0,0,0,0,0.0,0.000000,0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,0,0,Benign
1,60997457,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
2,61149019,5,0,1500,0,300,300,300.0,0.000000,0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,0,1,Benign
3,60997555,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
4,61997503,3,0,0,0,0,0,0.0,0.000000,0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,118494070,31,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,0,0,Benign
331096,114340,2,1,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331097,1404866,8,7,1132,1581,661,0,141.5,222.792023,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331098,3966663,14,7,1386,392,680,0,99.0,189.204814,291,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,Benign
331099,86637706,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [65]:
print(df_thursday2["Label"].value_counts()[['Benign']].sum())
print(df_thursday2["Label"].value_counts()[['Malicious']].sum())

187347
62142

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [66]:
df_thursday2.replace(to_replace="Benign", value=0, inplace=True)
df_thursday2.replace(to_replace="Malicious", value=1, inplace=True)

In [67]:
df_thursday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,115307855,5,0,0,0,0,0,0.0,0.000000,0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,0,0,0
1,60997457,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,0
2,61149019,5,0,1500,0,300,300,300.0,0.000000,0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,0,1,0
3,60997555,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,0
4,61997503,3,0,0,0,0,0,0.0,0.000000,0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,118494070,31,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,0,0,0
331096,114340,2,1,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
331097,1404866,8,7,1132,1581,661,0,141.5,222.792023,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
331098,3966663,14,7,1386,392,680,0,99.0,189.204814,291,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
331099,86637706,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,1,0,0

In [68]:
print(df_thursday2["Label"].value_counts()[[0]].sum())
print(df_thursday2["Label"].value_counts()[[1]].sum())

187347
62142

### 9- Saving dataset

In [69]:
df_thursday2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 249489 entries, 0 to 331099
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      249489 non-null  int64
 1   Tot Fwd Pkts       249489 non-null  int64
 2   Tot Bwd Pkts       249489 non-null  int64
 3   TotLen Fwd Pkts    249489 non-null  int64
 4   TotLen Bwd Pkts    249489 non-null  int64
 5   Fwd Pkt Len Max    249489 non-null  int64
 6   Fwd Pkt Len Min    249489 non-null  int64
 7   Fwd Pkt Len Mean   249489 non-null  float64
 8   Fwd Pkt Len Std    249489 non-null  float64
 9   Bwd Pkt Len Max    249489 non-null  int64
 10  Bwd Pkt Len Min    249489 non-null  int64
 11  Bwd Pkt Len Mean   249489 non-null  float64
 12  Bwd Pkt Len Std    249489 non-null  float64
 13  Flow IAT Mean      249489 non-null  float64
 14  Flow IAT Std       249489 non-null  float64
 15  Flow IAT Max       249489 non-null  int64
 16  Flow IAT Min       249489 non-null  int64
 17  Fwd IAT Tot        249489 non-null  int64
 18  Fwd IAT Mean       249489 non-null  float64
 19  Fwd IAT Std        249489 non-null  float64
 20  Fwd IAT Max        249489 non-null  int64
 21  Fwd IAT Min        249489 non-null  int64
 22  Bwd IAT Tot        249489 non-null  int64
 23  Bwd IAT Mean       249489 non-null  float64
 24  Bwd IAT Std        249489 non-null  float64
 25  Bwd IAT Max        249489 non-null  int64
 26  Bwd IAT Min        249489 non-null  int64
 27  Fwd Header Len     249489 non-null  int64
 28  Bwd Header Len     249489 non-null  int64
 29  Fwd Pkts/s         249489 non-null  float64
 30  Bwd Pkts/s         249489 non-null  float64
 31  Pkt Len Min        249489 non-null  int64
 32  Pkt Len Max        249489 non-null  int64
 33  Pkt Len Mean       249489 non-null  float64
 34  Pkt Len Std        249489 non-null  float64
 35  Pkt Len Var        249489 non-null  float64
 36  FIN Flag Cnt       249489 non-null  int64
 37  SYN Flag Cnt       249489 non-null  int64
 38  RST Flag Cnt       249489 non-null  int64
 39  PSH Flag Cnt       249489 non-null  int64
 40  ACK Flag Cnt       249489 non-null  int64
 41  URG Flag Cnt       249489 non-null  int64
 42  CWE Flag Count     249489 non-null  int64
 43  ECE Flag Cnt       249489 non-null  int64
 44  Down/Up Ratio      249489 non-null  int64
 45  Pkt Size Avg       249489 non-null  float64
 46  Fwd Seg Size Avg   249489 non-null  float64
 47  Bwd Seg Size Avg   249489 non-null  float64
 48  Fwd Byts/b Avg     249489 non-null  int64
 49  Fwd Pkts/b Avg     249489 non-null  int64
 50  Fwd Blk Rate Avg   249489 non-null  int64
 51  Bwd Byts/b Avg     249489 non-null  int64
 52  Bwd Pkts/b Avg     249489 non-null  int64
 53  Bwd Blk Rate Avg   249489 non-null  int64
 54  Subflow Fwd Pkts   249489 non-null  int64
 55  Subflow Fwd Byts   249489 non-null  int64
 56  Subflow Bwd Pkts   249489 non-null  int64
 57  Subflow Bwd Byts   249489 non-null  int64
 58  Init Fwd Win Byts  249489 non-null  int64
 59  Init Bwd Win Byts  249489 non-null  int64
 60  Fwd Act Data Pkts  249489 non-null  int64
 61  Fwd Seg Size Min   249489 non-null  int64
 62  Active Mean        249489 non-null  float64
 63  Active Std         249489 non-null  float64
 64  Active Max         249489 non-null  int64
 65  Active Min         249489 non-null  int64
 66  Idle Mean          249489 non-null  float64
 67  Idle Std           249489 non-null  float64
 68  Idle Max           249489 non-null  int64
 69  Idle Min           249489 non-null  int64
 70  Protocol_6         249489 non-null  uint8
 71  Protocol_17        249489 non-null  uint8
 72  Label              249489 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 137.5 MB

In [70]:
print(df_thursday2["Label"].value_counts()[[0]].sum())
print(df_thursday2["Label"].value_counts()[[1]].sum())

187347
62142

In [71]:
# take dataframe of benign of the first day
df_friday5_benign =  df_thursday2[df_thursday2["Label"]==0]
df_friday5_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,115307855,5,0,0,0,0,0,0.0,0.000000,0,...,0.0,1812348,1812348,56700000.0,6.010058e+06,61000000,52500000,0,0,0
1,60997457,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,0
2,61149019,5,0,1500,0,300,300,300.0,0.000000,0,...,0.0,3530939,3530939,19200000.0,1.250000e+07,32600000,7999725,0,1,0
3,60997555,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,61000000.0,0.000000e+00,61000000,61000000,0,0,0
4,61997503,3,0,0,0,0,0,0.0,0.000000,0,...,0.0,999909,999909,61000000.0,0.000000e+00,61000000,61000000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331095,118494070,31,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,0,0,0
331096,114340,2,1,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
331097,1404866,8,7,1132,1581,661,0,141.5,222.792023,1173,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
331098,3966663,14,7,1386,392,680,0,99.0,189.204814,291,...,0.0,0,0,0.0,0.000000e+00,0,0,1,0,0
331099,86637706,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,86600000.0,0.000000e+00,86600000,86600000,1,0,0

In [72]:
# take datafram of malicious of the first day
df_friday5_malicious = df_thursday2[df_thursday2["Label"]==1]
df_friday5_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
117644,1669202,8,7,1128,1581,661,0,141.000000,222.623321,1173,...,0.0,0,0,0.0,0.000,0,0,1,0,1
117645,1665774,8,7,1128,1581,661,0,141.000000,222.623321,1173,...,0.0,0,0,0.0,0.000,0,0,1,0,1
117646,447631,1,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000,0,0,1,0,1
117647,112634925,60,0,0,0,0,0,0.000000,0.000000,0,...,33700000.0,66100000,4952610,10200000.0,3990749.302,14100000,6109541,0,0,1
117648,2523028,11,7,1132,1581,661,0,102.909091,197.772321,1173,...,0.0,0,0,0.0,0.000,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294037,1395743,8,7,1132,1581,661,0,141.500000,222.792023,1173,...,0.0,0,0,0.0,0.000,0,0,1,0,1
294039,780351,5,3,53,131,53,0,10.600000,23.702321,131,...,0.0,0,0,0.0,0.000,0,0,1,0,1
294040,2937271,10,7,1148,1581,677,0,114.800000,210.092466,1173,...,0.0,0,0,0.0,0.000,0,0,1,0,1
294041,135614,3,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000,0,0,1,0,1
294043,3674777,9,7,1148,1581,677,0,127.555556,218.691056,1173,...,0.0,0,0,0.0,0.000,0,0,1,0,1

#### 2.3 Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv

In [73]:
df_thursday3 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-15-2018.csv')

In [74]:
df_thursday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,15/02/2018 08:25:18,112641158,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,Benign
1,22,6,15/02/2018 08:29:05,37366762,14,12,2168,2993,712,0,...,32,1024353.0,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,Benign
2,47514,6,15/02/2018 08:29:42,543,2,0,64,0,64,0,...,32,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
3,0,0,15/02/2018 08:28:07,112640703,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,Benign
4,0,0,15/02/2018 08:30:56,112640874,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,50111,6,15/02/2018 09:04:42,22,3,0,31,0,31,0,...,20,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
1048571,443,6,15/02/2018 09:03:55,54682783,5,1,123,46,46,0,...,20,158783.0,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,Benign
1048572,443,6,15/02/2018 09:03:56,53682093,5,1,123,46,46,0,...,20,259719.0,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,Benign
1048573,443,6,15/02/2018 09:03:55,54683364,5,1,123,46,46,0,...,20,158870.0,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,Benign
1048574,443,6,15/02/2018 09:02:01,116857161,18,17,1066,5265,281,0,...,20,221407.0,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,Benign

In [75]:
df_thursday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [76]:
df_thursday3["Label"].unique()

array(['Benign', 'DoS attacks-GoldenEye', 'DoS attacks-Slowloris'],
      dtype=object)

In [77]:
print(df_thursday3["Label"].value_counts()[['Benign']].sum())
print(df_thursday3["Label"].value_counts()[['DoS attacks-GoldenEye']].sum())
print(df_thursday3["Label"].value_counts()[['DoS attacks-Slowloris']].sum())

996077
41508
10990

### 2- Removing row with erroneous 'Label' label

In [79]:
# Remove erroneous 'Label' row
df_thursday3.drop(df_thursday3.loc[df_thursday3["Label"] == "Label"].index, inplace=True)

In [80]:
df_thursday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,15/02/2018 08:25:18,112641158,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,Benign
1,22,6,15/02/2018 08:29:05,37366762,14,12,2168,2993,712,0,...,32,1024353.0,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,Benign
2,47514,6,15/02/2018 08:29:42,543,2,0,64,0,64,0,...,32,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
3,0,0,15/02/2018 08:28:07,112640703,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,Benign
4,0,0,15/02/2018 08:30:56,112640874,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,50111,6,15/02/2018 09:04:42,22,3,0,31,0,31,0,...,20,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
1048571,443,6,15/02/2018 09:03:55,54682783,5,1,123,46,46,0,...,20,158783.0,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,Benign
1048572,443,6,15/02/2018 09:03:56,53682093,5,1,123,46,46,0,...,20,259719.0,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,Benign
1048573,443,6,15/02/2018 09:03:55,54683364,5,1,123,46,46,0,...,20,158870.0,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,Benign
1048574,443,6,15/02/2018 09:02:01,116857161,18,17,1066,5265,281,0,...,20,221407.0,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [85]:
df_thursday3.replace(to_replace=['DoS attacks-GoldenEye'], value="Malicious", inplace=True)
df_thursday3.replace(to_replace=['DoS attacks-Slowloris'], value="Malicious", inplace=True)

In [86]:
df_thursday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,15/02/2018 08:25:18,112641158,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,Benign
1,22,6,15/02/2018 08:29:05,37366762,14,12,2168,2993,712,0,...,32,1024353.0,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,Benign
2,47514,6,15/02/2018 08:29:42,543,2,0,64,0,64,0,...,32,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
3,0,0,15/02/2018 08:28:07,112640703,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,Benign
4,0,0,15/02/2018 08:30:56,112640874,3,0,0,0,0,0,...,0,0.0,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,50111,6,15/02/2018 09:04:42,22,3,0,31,0,31,0,...,20,0.0,0.000000,0,0,0.0,0.000000e+00,0,0,Benign
1048571,443,6,15/02/2018 09:03:55,54682783,5,1,123,46,46,0,...,20,158783.0,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,Benign
1048572,443,6,15/02/2018 09:03:56,53682093,5,1,123,46,46,0,...,20,259719.0,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,Benign
1048573,443,6,15/02/2018 09:03:55,54683364,5,1,123,46,46,0,...,20,158870.0,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,Benign
1048574,443,6,15/02/2018 09:02:01,116857161,18,17,1066,5265,281,0,...,20,221407.0,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,Benign

In [87]:
df_thursday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [88]:
print(df_thursday3["Label"].value_counts()[['Benign']].sum())
print(df_thursday3["Label"].value_counts()[['Malicious']].sum())

996077
52498

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [89]:
df_thursday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [90]:
df_thursday3["Protocol"].unique()

array([ 0,  6, 17])

In [91]:
df_thursday3 = pd.get_dummies(df_thursday3, columns=['Protocol'], drop_first=True)
df_thursday3

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,0,15/02/2018 08:25:18,112641158,3,0,0,0,0,0,0.000000,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,Benign,0,0
1,22,15/02/2018 08:29:05,37366762,14,12,2168,2993,712,0,154.857143,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,Benign,1,0
2,47514,15/02/2018 08:29:42,543,2,0,64,0,64,0,32.000000,...,0.000000,0,0,0.0,0.000000e+00,0,0,Benign,1,0
3,0,15/02/2018 08:28:07,112640703,3,0,0,0,0,0,0.000000,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,Benign,0,0
4,0,15/02/2018 08:30:56,112640874,3,0,0,0,0,0,0.000000,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,Benign,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,50111,15/02/2018 09:04:42,22,3,0,31,0,31,0,10.333333,...,0.000000,0,0,0.0,0.000000e+00,0,0,Benign,1,0
1048571,443,15/02/2018 09:03:55,54682783,5,1,123,46,46,0,24.600000,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,Benign,1,0
1048572,443,15/02/2018 09:03:56,53682093,5,1,123,46,46,0,24.600000,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,Benign,1,0
1048573,443,15/02/2018 09:03:55,54683364,5,1,123,46,46,0,24.600000,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,Benign,1,0
1048574,443,15/02/2018 09:02:01,116857161,18,17,1066,5265,281,0,59.222222,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,Benign,1,0

In [92]:
# making Label column the last column again
df_thursday3.insert(len(df_thursday3.columns)-1, 'Label', df_thursday3.pop('Label'))

In [93]:
df_thursday3

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,0,15/02/2018 08:25:18,112641158,3,0,0,0,0,0,0.000000,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,0,0,Benign
1,22,15/02/2018 08:29:05,37366762,14,12,2168,2993,712,0,154.857143,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,1,0,Benign
2,47514,15/02/2018 08:29:42,543,2,0,64,0,64,0,32.000000,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
3,0,15/02/2018 08:28:07,112640703,3,0,0,0,0,0,0.000000,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,0,0,Benign
4,0,15/02/2018 08:30:56,112640874,3,0,0,0,0,0,0.000000,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,50111,15/02/2018 09:04:42,22,3,0,31,0,31,0,10.333333,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048571,443,15/02/2018 09:03:55,54682783,5,1,123,46,46,0,24.600000,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,1,0,Benign
1048572,443,15/02/2018 09:03:56,53682093,5,1,123,46,46,0,24.600000,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,1,0,Benign
1048573,443,15/02/2018 09:03:55,54683364,5,1,123,46,46,0,24.600000,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,1,0,Benign
1048574,443,15/02/2018 09:02:01,116857161,18,17,1066,5265,281,0,59.222222,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [94]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [95]:
df_thursday3.drop(columns=columns_to_drop, inplace=True)

In [96]:
df_thursday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641158,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,0,0,Benign
1,37366762,14,12,2168,2993,712,0,154.857143,254.855270,976,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,1,0,Benign
2,543,2,0,64,0,64,0,32.000000,45.254834,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
3,112640703,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,0,0,Benign
4,112640874,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,22,3,0,31,0,31,0,10.333333,17.897858,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048571,54682783,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,1,0,Benign
1048572,53682093,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,1,0,Benign
1048573,54683364,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,1,0,Benign
1048574,116857161,18,17,1066,5265,281,0,59.222222,87.686980,1460,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,1,0,Benign

### 6- Dropping missing or duplicate values

In [97]:
df_thursday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [98]:
df_thursday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [99]:
df_thursday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641158,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,0,0,Benign
1,37366762,14,12,2168,2993,712,0,154.857143,254.855270,976,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,1,0,Benign
2,543,2,0,64,0,64,0,32.000000,45.254834,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
3,112640703,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,0,0,Benign
4,112640874,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,22,3,0,31,0,31,0,10.333333,17.897858,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
1048571,54682783,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,1,0,Benign
1048572,53682093,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,1,0,Benign
1048573,54683364,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,1,0,Benign
1048574,116857161,18,17,1066,5265,281,0,59.222222,87.686980,1460,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,1,0,Benign

In [100]:
df_thursday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [101]:
df_thursday3.drop_duplicates(inplace=True)

In [102]:
df_thursday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641158,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,0,0,Benign
1,37366762,14,12,2168,2993,712,0,154.857143,254.855270,976,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,1,0,Benign
2,543,2,0,64,0,64,0,32.000000,45.254834,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,Benign
3,112640703,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,0,0,Benign
4,112640874,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,53668766,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,159832,159832,53508712.0,0.000000e+00,53508712,53508712,1,0,Benign
1048571,54682783,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,1,0,Benign
1048572,53682093,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,1,0,Benign
1048573,54683364,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,1,0,Benign
1048574,116857161,18,17,1066,5265,281,0,59.222222,87.686980,1460,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [103]:
print(df_thursday3["Label"].value_counts()[['Benign']].sum())
print(df_thursday3["Label"].value_counts()[['Malicious']].sum())

744261
51314

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [104]:
df_thursday3.replace(to_replace="Benign", value=0, inplace=True)
df_thursday3.replace(to_replace="Malicious", value=1, inplace=True)

In [105]:
df_thursday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641158,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,0,0,0
1,37366762,14,12,2168,2993,712,0,154.857143,254.855270,976,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,1,0,0
2,543,2,0,64,0,64,0,32.000000,45.254834,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,0
3,112640703,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,0,0,0
4,112640874,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,53668766,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,159832,159832,53508712.0,0.000000e+00,53508712,53508712,1,0,0
1048571,54682783,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,1,0,0
1048572,53682093,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,1,0,0
1048573,54683364,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,1,0,0
1048574,116857161,18,17,1066,5265,281,0,59.222222,87.686980,1460,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,1,0,0

In [106]:
print(df_thursday3["Label"].value_counts()[[0]].sum())
print(df_thursday3["Label"].value_counts()[[1]].sum())

744261
51314

### 9- Saving dataset

In [107]:
df_thursday3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 795575 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      795575 non-null  int64
 1   Tot Fwd Pkts       795575 non-null  int64
 2   Tot Bwd Pkts       795575 non-null  int64
 3   TotLen Fwd Pkts    795575 non-null  int64
 4   TotLen Bwd Pkts    795575 non-null  int64
 5   Fwd Pkt Len Max    795575 non-null  int64
 6   Fwd Pkt Len Min    795575 non-null  int64
 7   Fwd Pkt Len Mean   795575 non-null  float64
 8   Fwd Pkt Len Std    795575 non-null  float64
 9   Bwd Pkt Len Max    795575 non-null  int64
 10  Bwd Pkt Len Min    795575 non-null  int64
 11  Bwd Pkt Len Mean   795575 non-null  float64
 12  Bwd Pkt Len Std    795575 non-null  float64
 13  Flow IAT Mean      795575 non-null  float64
 14  Flow IAT Std       795575 non-null  float64
 15  Flow IAT Max       795575 non-null  int64
 16  Flow IAT Min       795575 non-null  int64
 17  Fwd IAT Tot        795575 non-null  int64
 18  Fwd IAT Mean       795575 non-null  float64
 19  Fwd IAT Std        795575 non-null  float64
 20  Fwd IAT Max        795575 non-null  int64
 21  Fwd IAT Min        795575 non-null  int64
 22  Bwd IAT Tot        795575 non-null  int64
 23  Bwd IAT Mean       795575 non-null  float64
 24  Bwd IAT Std        795575 non-null  float64
 25  Bwd IAT Max        795575 non-null  int64
 26  Bwd IAT Min        795575 non-null  int64
 27  Fwd Header Len     795575 non-null  int64
 28  Bwd Header Len     795575 non-null  int64
 29  Fwd Pkts/s         795575 non-null  float64
 30  Bwd Pkts/s         795575 non-null  float64
 31  Pkt Len Min        795575 non-null  int64
 32  Pkt Len Max        795575 non-null  int64
 33  Pkt Len Mean       795575 non-null  float64
 34  Pkt Len Std        795575 non-null  float64
 35  Pkt Len Var        795575 non-null  float64
 36  FIN Flag Cnt       795575 non-null  int64
 37  SYN Flag Cnt       795575 non-null  int64
 38  RST Flag Cnt       795575 non-null  int64
 39  PSH Flag Cnt       795575 non-null  int64
 40  ACK Flag Cnt       795575 non-null  int64
 41  URG Flag Cnt       795575 non-null  int64
 42  CWE Flag Count     795575 non-null  int64
 43  ECE Flag Cnt       795575 non-null  int64
 44  Down/Up Ratio      795575 non-null  int64
 45  Pkt Size Avg       795575 non-null  float64
 46  Fwd Seg Size Avg   795575 non-null  float64
 47  Bwd Seg Size Avg   795575 non-null  float64
 48  Fwd Byts/b Avg     795575 non-null  int64
 49  Fwd Pkts/b Avg     795575 non-null  int64
 50  Fwd Blk Rate Avg   795575 non-null  int64
 51  Bwd Byts/b Avg     795575 non-null  int64
 52  Bwd Pkts/b Avg     795575 non-null  int64
 53  Bwd Blk Rate Avg   795575 non-null  int64
 54  Subflow Fwd Pkts   795575 non-null  int64
 55  Subflow Fwd Byts   795575 non-null  int64
 56  Subflow Bwd Pkts   795575 non-null  int64
 57  Subflow Bwd Byts   795575 non-null  int64
 58  Init Fwd Win Byts  795575 non-null  int64
 59  Init Bwd Win Byts  795575 non-null  int64
 60  Fwd Act Data Pkts  795575 non-null  int64
 61  Fwd Seg Size Min   795575 non-null  int64
 62  Active Mean        795575 non-null  float64
 63  Active Std         795575 non-null  float64
 64  Active Max         795575 non-null  int64
 65  Active Min         795575 non-null  int64
 66  Idle Mean          795575 non-null  float64
 67  Idle Std           795575 non-null  float64
 68  Idle Max           795575 non-null  int64
 69  Idle Min           795575 non-null  int64
 70  Protocol_6         795575 non-null  uint8
 71  Protocol_17        795575 non-null  uint8
 72  Label              795575 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 438.5 MB

In [108]:
print(df_thursday3["Label"].value_counts()[[0]].sum())
print(df_thursday3["Label"].value_counts()[[1]].sum())

744261
51314

In [109]:
# take dataframe of benign of the first day
df_friday6_benign =  df_thursday3[df_thursday3["Label"]==0]
df_friday6_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641158,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320579.0,7.042784e+02,56321077,56320081,0,0,0
1,37366762,14,12,2168,2993,712,0,154.857143,254.855270,976,...,649038.754495,1601183,321569,11431221.0,3.644991e+06,15617415,8960247,1,0,0
2,543,2,0,64,0,64,0,32.000000,45.254834,0,...,0.000000,0,0,0.0,0.000000e+00,0,0,1,0,0
3,112640703,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320351.5,3.669884e+02,56320611,56320092,0,0,0
4,112640874,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000,0,0,56320437.0,7.198347e+02,56320946,56319928,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,53668766,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,159832,159832,53508712.0,0.000000e+00,53508712,53508712,1,0,0
1048571,54682783,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158783,158783,54523813.0,0.000000e+00,54523813,54523813,1,0,0
1048572,53682093,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,259719,259719,53421756.0,0.000000e+00,53421756,53421756,1,0,0
1048573,54683364,5,1,123,46,46,0,24.600000,23.276598,46,...,0.000000,158870,158870,54523593.0,0.000000e+00,54523593,54523593,1,0,0
1048574,116857161,18,17,1066,5265,281,0,59.222222,87.686980,1460,...,48231.753545,255512,187302,58082282.0,1.832213e+05,58211839,57952725,1,0,0

In [110]:
# take datafram of malicious of the first day
df_friday6_malicious = df_thursday3[df_thursday3["Label"]==1]
df_friday6_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
44,6010454,4,4,285,972,285,0,71.250000,142.500000,972,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
45,6005042,4,4,422,662,422,0,105.500000,211.000000,662,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
46,6003639,4,4,548,972,548,0,137.000000,274.000000,972,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
47,5998377,4,4,327,972,327,0,81.750000,163.500000,972,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
48,5999806,4,4,378,972,378,0,94.500000,189.000000,972,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54418,108637149,15,3,2530,0,230,0,168.666667,105.279673,0,...,2.464894e+06,7777810,4291923,24141850.00,2.056720e+07,53222622,6668068,1,0,1
54419,34280663,2,0,0,0,0,0,0.000000,0.000000,0,...,0.000000e+00,0,0,34280663.00,0.000000e+00,34280663,34280663,1,0,1
54420,1993693,2,0,0,0,0,0,0.000000,0.000000,0,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
54421,3047742,3,0,0,0,0,0,0.000000,0.000000,0,...,0.000000e+00,0,0,0.00,0.000000e+00,0,0,1,0,1
54422,107511923,15,3,2530,0,230,0,168.666667,105.279673,0,...,2.344699e+06,7705176,4389271,23854368.75,2.059115e+07,53217184,6658108,1,0,1

#### 2.4 Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv

In [116]:
df_thursday4 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-22-2018.csv')

In [117]:
df_thursday4

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,...,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,...,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,17,22/02/2018 09:57:34,61898,2,2,78,254,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048571,1500,6,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,...,20,0.0,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign
1048572,53,17,22/02/2018 03:52:37,642,1,1,39,67,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048573,53,17,22/02/2018 09:40:42,78472,1,1,32,121,32,32,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048574,3389,6,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign

In [118]:
df_thursday4.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [119]:
df_thursday4["Label"].unique()

array(['Benign', 'Brute Force -Web', 'Brute Force -XSS', 'SQL Injection'],
      dtype=object)

In [120]:
print(df_thursday4["Label"].value_counts()[['Benign']].sum())
print(df_thursday4["Label"].value_counts()[['Brute Force -Web']].sum())
print(df_thursday4["Label"].value_counts()[['Brute Force -XSS']].sum())
print(df_thursday4["Label"].value_counts()[['SQL Injection']].sum())

1048213
249
79
34

### 2- Removing row with erroneous 'Label' label

In [122]:
# Remove erroneous 'Label' row
df_thursday4.drop(df_thursday4.loc[df_thursday4["Label"] == "Label"].index, inplace=True)

In [123]:
df_thursday4

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,...,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,...,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,17,22/02/2018 09:57:34,61898,2,2,78,254,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048571,1500,6,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,...,20,0.0,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign
1048572,53,17,22/02/2018 03:52:37,642,1,1,39,67,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048573,53,17,22/02/2018 09:40:42,78472,1,1,32,121,32,32,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048574,3389,6,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [124]:
df_thursday4.replace(to_replace=['Brute Force -Web'], value="Malicious", inplace=True)
df_thursday4.replace(to_replace=['Brute Force -XSS'], value="Malicious", inplace=True)
df_thursday4.replace(to_replace=['SQL Injection'], value="Malicious", inplace=True)

In [125]:
df_thursday4

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,...,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,...,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,17,22/02/2018 09:57:34,61898,2,2,78,254,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048571,1500,6,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,...,20,0.0,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign
1048572,53,17,22/02/2018 03:52:37,642,1,1,39,67,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048573,53,17,22/02/2018 09:40:42,78472,1,1,32,121,32,32,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048574,3389,6,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign

In [126]:
df_thursday4["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [127]:
print(df_thursday4["Label"].value_counts()[['Benign']].sum())
print(df_thursday4["Label"].value_counts()[['Malicious']].sum())

1048213
362

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [128]:
df_thursday4.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [129]:
df_thursday4["Protocol"].unique()

array([ 6, 17,  0])

In [130]:
df_thursday4 = pd.get_dummies(df_thursday4, columns=['Protocol'], drop_first=True)
df_thursday4

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,22,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,106.3,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign,1,0
1,34989,22/02/2018 08:26:24,790,2,0,848,0,848,0,424.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,1,0
2,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign,0,1
3,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign,0,1
4,500,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,500.0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,22/02/2018 09:57:34,61898,2,2,78,254,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,0,1
1048571,1500,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,0.0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign,1,0
1048572,53,22/02/2018 03:52:37,642,1,1,39,67,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,0,1
1048573,53,22/02/2018 09:40:42,78472,1,1,32,121,32,32,32.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,0,1
1048574,3389,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,143.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,1,0

In [131]:
# making Label column the last column again
df_thursday4.insert(len(df_thursday4.columns)-1, 'Label', df_thursday4.pop('Label'))

In [132]:
df_thursday4

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,22,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,106.3,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,34989,22/02/2018 08:26:24,790,2,0,848,0,848,0,424.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,500,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,500.0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,22/02/2018 09:57:34,61898,2,2,78,254,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,1500,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,0.0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,53,22/02/2018 03:52:37,642,1,1,39,67,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,53,22/02/2018 09:40:42,78472,1,1,32,121,32,32,32.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,3389,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,143.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [133]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [134]:
df_thursday4.drop(columns=columns_to_drop, inplace=True)

In [135]:
df_thursday4

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,642,1,1,39,67,39,39,39.0,0.000000,67,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 6- Dropping missing or duplicate values

In [136]:
df_thursday4["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [137]:
df_thursday4["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [138]:
df_thursday4

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,642,1,1,39,67,39,39,39.0,0.000000,67,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

In [139]:
df_thursday4["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [140]:
df_thursday4.drop_duplicates(inplace=True)

In [141]:
df_thursday4

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [142]:
print(df_thursday4["Label"].value_counts()[['Benign']].sum())
print(df_thursday4["Label"].value_counts()[['Malicious']].sum())

830547
338

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [143]:
df_thursday4.replace(to_replace="Benign", value=0, inplace=True)
df_thursday4.replace(to_replace="Malicious", value=1, inplace=True)

In [144]:
df_thursday4

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [145]:
print(df_thursday4["Label"].value_counts()[[0]].sum())
print(df_thursday4["Label"].value_counts()[[1]].sum())

830547
338

### 9- Saving dataset

In [146]:
df_thursday4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830885 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      830885 non-null  int64
 1   Tot Fwd Pkts       830885 non-null  int64
 2   Tot Bwd Pkts       830885 non-null  int64
 3   TotLen Fwd Pkts    830885 non-null  int64
 4   TotLen Bwd Pkts    830885 non-null  int64
 5   Fwd Pkt Len Max    830885 non-null  int64
 6   Fwd Pkt Len Min    830885 non-null  int64
 7   Fwd Pkt Len Mean   830885 non-null  float64
 8   Fwd Pkt Len Std    830885 non-null  float64
 9   Bwd Pkt Len Max    830885 non-null  int64
 10  Bwd Pkt Len Min    830885 non-null  int64
 11  Bwd Pkt Len Mean   830885 non-null  float64
 12  Bwd Pkt Len Std    830885 non-null  float64
 13  Flow IAT Mean      830885 non-null  float64
 14  Flow IAT Std       830885 non-null  float64
 15  Flow IAT Max       830885 non-null  int64
 16  Flow IAT Min       830885 non-null  int64
 17  Fwd IAT Tot        830885 non-null  int64
 18  Fwd IAT Mean       830885 non-null  float64
 19  Fwd IAT Std        830885 non-null  float64
 20  Fwd IAT Max        830885 non-null  int64
 21  Fwd IAT Min        830885 non-null  int64
 22  Bwd IAT Tot        830885 non-null  int64
 23  Bwd IAT Mean       830885 non-null  float64
 24  Bwd IAT Std        830885 non-null  float64
 25  Bwd IAT Max        830885 non-null  int64
 26  Bwd IAT Min        830885 non-null  int64
 27  Fwd Header Len     830885 non-null  int64
 28  Bwd Header Len     830885 non-null  int64
 29  Fwd Pkts/s         830885 non-null  float64
 30  Bwd Pkts/s         830885 non-null  float64
 31  Pkt Len Min        830885 non-null  int64
 32  Pkt Len Max        830885 non-null  int64
 33  Pkt Len Mean       830885 non-null  float64
 34  Pkt Len Std        830885 non-null  float64
 35  Pkt Len Var        830885 non-null  float64
 36  FIN Flag Cnt       830885 non-null  int64
 37  SYN Flag Cnt       830885 non-null  int64
 38  RST Flag Cnt       830885 non-null  int64
 39  PSH Flag Cnt       830885 non-null  int64
 40  ACK Flag Cnt       830885 non-null  int64
 41  URG Flag Cnt       830885 non-null  int64
 42  CWE Flag Count     830885 non-null  int64
 43  ECE Flag Cnt       830885 non-null  int64
 44  Down/Up Ratio      830885 non-null  int64
 45  Pkt Size Avg       830885 non-null  float64
 46  Fwd Seg Size Avg   830885 non-null  float64
 47  Bwd Seg Size Avg   830885 non-null  float64
 48  Fwd Byts/b Avg     830885 non-null  int64
 49  Fwd Pkts/b Avg     830885 non-null  int64
 50  Fwd Blk Rate Avg   830885 non-null  int64
 51  Bwd Byts/b Avg     830885 non-null  int64
 52  Bwd Pkts/b Avg     830885 non-null  int64
 53  Bwd Blk Rate Avg   830885 non-null  int64
 54  Subflow Fwd Pkts   830885 non-null  int64
 55  Subflow Fwd Byts   830885 non-null  int64
 56  Subflow Bwd Pkts   830885 non-null  int64
 57  Subflow Bwd Byts   830885 non-null  int64
 58  Init Fwd Win Byts  830885 non-null  int64
 59  Init Bwd Win Byts  830885 non-null  int64
 60  Fwd Act Data Pkts  830885 non-null  int64
 61  Fwd Seg Size Min   830885 non-null  int64
 62  Active Mean        830885 non-null  float64
 63  Active Std         830885 non-null  float64
 64  Active Max         830885 non-null  int64
 65  Active Min         830885 non-null  int64
 66  Idle Mean          830885 non-null  float64
 67  Idle Std           830885 non-null  float64
 68  Idle Max           830885 non-null  int64
 69  Idle Min           830885 non-null  int64
 70  Protocol_6         830885 non-null  uint8
 71  Protocol_17        830885 non-null  uint8
 72  Label              830885 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 458.0 MB

In [147]:
print(df_thursday4["Label"].value_counts()[[0]].sum())
print(df_thursday4["Label"].value_counts()[[1]].sum())

830547
338

In [148]:
# take dataframe of benign of the first day
df_friday7_benign =  df_thursday4[df_thursday4["Label"]==0]
df_friday7_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [149]:
# take datafram of malicious of the first day
df_friday7_malicious = df_thursday4[df_thursday4["Label"]==1]
df_friday7_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
295,6499677,13,10,2333,4425,431,0,179.461538,177.733234,1048,...,0.0,0,0,0.0,0.0,0,0,1,0,1
296,46,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
297,6397036,4,7,372,9375,372,0,93.000000,186.000000,2920,...,0.0,0,0,0.0,0.0,0,0,1,0,1
298,6,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
299,5022507,4,4,599,364,599,0,149.750000,299.500000,364,...,0.0,0,0,0.0,0.0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,5007623,5,3,694,1903,694,0,138.800000,310.366235,1903,...,0.0,0,0,0.0,0.0,0,0,1,0,1
1677,5011797,5,3,704,2033,704,0,140.800000,314.838371,2033,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2024,5934694,21,11,5132,16976,680,0,244.380952,300.648711,1933,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2497,6860324,28,15,7294,23629,680,0,260.500000,296.445798,2521,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2824,226,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1

### 3- Wednesday logs

#### 3.1 Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv

In [155]:
df_wednesday1 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-14-2018.csv')

In [151]:
df_wednesday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign

In [152]:
df_wednesday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [153]:
df_wednesday1["Label"].unique()

array(['Benign', 'FTP-BruteForce', 'SSH-Bruteforce'], dtype=object)

In [154]:
print(df_wednesday1["Label"].value_counts()[['Benign']].sum())
print(df_wednesday1["Label"].value_counts()[['FTP-BruteForce']].sum())
print(df_wednesday1["Label"].value_counts()[['SSH-Bruteforce']].sum())

667626
193360
187589

### 2- Removing row with erroneous 'Label' label

In [156]:
# Remove erroneous 'Label' row
df_wednesday1.drop(df_wednesday1.loc[df_wednesday1["Label"] == "Label"].index, inplace=True)

In [157]:
df_wednesday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [158]:
df_wednesday1.replace(to_replace=['FTP-BruteForce'], value="Malicious", inplace=True)
df_wednesday1.replace(to_replace=['SSH-Bruteforce'], value="Malicious", inplace=True)

In [159]:
df_wednesday1

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign

In [160]:
df_wednesday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [161]:
print(df_wednesday1["Label"].value_counts()[['Benign']].sum())
print(df_wednesday1["Label"].value_counts()[['Malicious']].sum())

667626
380949

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [162]:
df_wednesday1.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [163]:
df_wednesday1["Protocol"].unique()

array([ 0,  6, 17])

In [164]:
df_wednesday1 = pd.get_dummies(df_wednesday1, columns=['Protocol'], drop_first=True)
df_wednesday1

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,0.000000,...,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign,0,0
1,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,0.000000,...,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign,0,0
2,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,0.000000,...,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign,0,0
3,22,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,82.600000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
4,22,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,81.642857,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,217.800000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048571,80,14/02/2018 10:53:33,117,2,0,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048572,80,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048573,80,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048574,443,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,54.500000,...,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign,1,0

In [165]:
# making Label column the last column again
df_wednesday1.insert(len(df_wednesday1.columns)-1, 'Label', df_wednesday1.pop('Label'))

In [166]:
df_wednesday1

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,0.000000,...,0.0,0,0,56320859.5,139.300036,56320958,56320761,0,0,Benign
1,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,0.000000,...,0.0,0,0,56320733.0,114.551299,56320814,56320652,0,0,Benign
2,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,0.000000,...,0.0,0,0,56319311.5,301.934596,56319525,56319098,0,0,Benign
3,22,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,82.600000,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
4,22,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,81.642857,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,217.800000,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048571,80,14/02/2018 10:53:33,117,2,0,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048572,80,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048573,80,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048574,443,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,54.500000,...,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [167]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [168]:
df_wednesday1.drop(columns=columns_to_drop, inplace=True)

In [169]:
df_wednesday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641719,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56320859.5,139.300036,56320958,56320761,0,0,Benign
1,112641466,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56320733.0,114.551299,56320814,56320652,0,0,Benign
2,112638623,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56319311.5,301.934596,56319525,56319098,0,0,Benign
3,6453966,15,10,1239,2273,744,0,82.600000,196.741237,976,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
4,8804066,14,11,1143,2209,744,0,81.642857,203.745545,976,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,10156986,5,5,1089,1923,587,0,217.800000,299.745225,1334,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048571,117,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048572,5095331,3,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048573,5235511,3,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048574,5807256,6,4,327,145,245,0,54.500000,95.671835,145,...,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,1,0,Benign

### 6- Dropping missing or duplicate values

In [170]:
df_wednesday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [171]:
df_wednesday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [172]:
df_wednesday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,112641719,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56320859.5,139.300036,56320958,56320761,0,0,Benign
1,112641466,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56320733.0,114.551299,56320814,56320652,0,0,Benign
2,112638623,3,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,56319311.5,301.934596,56319525,56319098,0,0,Benign
3,6453966,15,10,1239,2273,744,0,82.600000,196.741237,976,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
4,8804066,14,11,1143,2209,744,0,81.642857,203.745545,976,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,10156986,5,5,1089,1923,587,0,217.800000,299.745225,1334,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048571,117,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048572,5095331,3,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048573,5235511,3,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.000000,0,0,1,0,Benign
1048574,5807256,6,4,327,145,245,0,54.500000,95.671835,145,...,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,1,0,Benign

In [173]:
df_wednesday1["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday1.drop_duplicates(inplace=True)

In [ ]:
df_wednesday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [ ]:
print(df_wednesday1["Label"].value_counts()[['Benign']].sum())
print(df_wednesday1["Label"].value_counts()[['Malicious']].sum())

830547
338

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [ ]:
df_wednesday1.replace(to_replace="Benign", value=0, inplace=True)
df_wednesday1.replace(to_replace="Malicious", value=1, inplace=True)

In [ ]:
df_wednesday1

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [ ]:
print(df_wednesday1["Label"].value_counts()[[0]].sum())
print(df_wednesday1["Label"].value_counts()[[1]].sum())

830547
338

### 9- Saving dataset

In [ ]:
df_wednesday1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830885 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      830885 non-null  int64
 1   Tot Fwd Pkts       830885 non-null  int64
 2   Tot Bwd Pkts       830885 non-null  int64
 3   TotLen Fwd Pkts    830885 non-null  int64
 4   TotLen Bwd Pkts    830885 non-null  int64
 5   Fwd Pkt Len Max    830885 non-null  int64
 6   Fwd Pkt Len Min    830885 non-null  int64
 7   Fwd Pkt Len Mean   830885 non-null  float64
 8   Fwd Pkt Len Std    830885 non-null  float64
 9   Bwd Pkt Len Max    830885 non-null  int64
 10  Bwd Pkt Len Min    830885 non-null  int64
 11  Bwd Pkt Len Mean   830885 non-null  float64
 12  Bwd Pkt Len Std    830885 non-null  float64
 13  Flow IAT Mean      830885 non-null  float64
 14  Flow IAT Std       830885 non-null  float64
 15  Flow IAT Max       830885 non-null  int64
 16  Flow IAT Min       830885 non-null  int64
 17  Fwd IAT Tot        830885 non-null  int64
 18  Fwd IAT Mean       830885 non-null  float64
 19  Fwd IAT Std        830885 non-null  float64
 20  Fwd IAT Max        830885 non-null  int64
 21  Fwd IAT Min        830885 non-null  int64
 22  Bwd IAT Tot        830885 non-null  int64
 23  Bwd IAT Mean       830885 non-null  float64
 24  Bwd IAT Std        830885 non-null  float64
 25  Bwd IAT Max        830885 non-null  int64
 26  Bwd IAT Min        830885 non-null  int64
 27  Fwd Header Len     830885 non-null  int64
 28  Bwd Header Len     830885 non-null  int64
 29  Fwd Pkts/s         830885 non-null  float64
 30  Bwd Pkts/s         830885 non-null  float64
 31  Pkt Len Min        830885 non-null  int64
 32  Pkt Len Max        830885 non-null  int64
 33  Pkt Len Mean       830885 non-null  float64
 34  Pkt Len Std        830885 non-null  float64
 35  Pkt Len Var        830885 non-null  float64
 36  FIN Flag Cnt       830885 non-null  int64
 37  SYN Flag Cnt       830885 non-null  int64
 38  RST Flag Cnt       830885 non-null  int64
 39  PSH Flag Cnt       830885 non-null  int64
 40  ACK Flag Cnt       830885 non-null  int64
 41  URG Flag Cnt       830885 non-null  int64
 42  CWE Flag Count     830885 non-null  int64
 43  ECE Flag Cnt       830885 non-null  int64
 44  Down/Up Ratio      830885 non-null  int64
 45  Pkt Size Avg       830885 non-null  float64
 46  Fwd Seg Size Avg   830885 non-null  float64
 47  Bwd Seg Size Avg   830885 non-null  float64
 48  Fwd Byts/b Avg     830885 non-null  int64
 49  Fwd Pkts/b Avg     830885 non-null  int64
 50  Fwd Blk Rate Avg   830885 non-null  int64
 51  Bwd Byts/b Avg     830885 non-null  int64
 52  Bwd Pkts/b Avg     830885 non-null  int64
 53  Bwd Blk Rate Avg   830885 non-null  int64
 54  Subflow Fwd Pkts   830885 non-null  int64
 55  Subflow Fwd Byts   830885 non-null  int64
 56  Subflow Bwd Pkts   830885 non-null  int64
 57  Subflow Bwd Byts   830885 non-null  int64
 58  Init Fwd Win Byts  830885 non-null  int64
 59  Init Bwd Win Byts  830885 non-null  int64
 60  Fwd Act Data Pkts  830885 non-null  int64
 61  Fwd Seg Size Min   830885 non-null  int64
 62  Active Mean        830885 non-null  float64
 63  Active Std         830885 non-null  float64
 64  Active Max         830885 non-null  int64
 65  Active Min         830885 non-null  int64
 66  Idle Mean          830885 non-null  float64
 67  Idle Std           830885 non-null  float64
 68  Idle Max           830885 non-null  int64
 69  Idle Min           830885 non-null  int64
 70  Protocol_6         830885 non-null  uint8
 71  Protocol_17        830885 non-null  uint8
 72  Label              830885 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 458.0 MB

In [ ]:
print(df_wednesday1["Label"].value_counts()[[0]].sum())
print(df_wednesday1["Label"].value_counts()[[1]].sum())

830547
338

In [ ]:
# take dataframe of benign of the first day
df_friday8_benign =  df_wednesday1[df_wednesday1["Label"]==0]
df_friday8_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [ ]:
# take datafram of malicious of the first day
df_friday8_malicious = df_wednesday1[df_wednesday1["Label"]==1]
df_friday8_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
295,6499677,13,10,2333,4425,431,0,179.461538,177.733234,1048,...,0.0,0,0,0.0,0.0,0,0,1,0,1
296,46,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
297,6397036,4,7,372,9375,372,0,93.000000,186.000000,2920,...,0.0,0,0,0.0,0.0,0,0,1,0,1
298,6,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
299,5022507,4,4,599,364,599,0,149.750000,299.500000,364,...,0.0,0,0,0.0,0.0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,5007623,5,3,694,1903,694,0,138.800000,310.366235,1903,...,0.0,0,0,0.0,0.0,0,0,1,0,1
1677,5011797,5,3,704,2033,704,0,140.800000,314.838371,2033,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2024,5934694,21,11,5132,16976,680,0,244.380952,300.648711,1933,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2497,6860324,28,15,7294,23629,680,0,260.500000,296.445798,2521,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2824,226,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1

#### 3.2 Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv

In [63]:
df_wednesday2 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-21-2018.csv')

In [64]:
df_wednesday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,6,21/02/2018 08:33:25,37953,5,3,135,127,135,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,500,17,21/02/2018 08:33:06,117573474,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58800000.0,23800000.0,75600000,42000000,Benign
2,500,17,21/02/2018 08:33:06,117573474,3,0,1500,0,500,500,...,8,0.0,0.0,0,0,58800000.0,23800000.0,75600000,42000000,Benign
3,500,17,21/02/2018 08:33:11,99743998,5,0,2500,0,500,500,...,8,4000290.0,0.0,4000290,4000290,31900000.0,37900000.0,75600000,7200397,Benign
4,500,17,21/02/2018 08:33:11,99743999,5,0,2500,0,500,500,...,8,4000286.0,0.0,4000286,4000286,31900000.0,37900000.0,75600000,7200399,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,55484,6,21/02/2018 02:33:29,1252,5,2,935,274,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048571,57624,6,21/02/2018 02:33:29,19055,5,2,935,341,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048572,57623,6,21/02/2018 02:33:29,36677,5,2,935,341,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048573,57625,6,21/02/2018 02:33:29,1849,5,2,935,341,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1048574,58120,6,21/02/2018 02:33:29,20580,5,2,935,299,935,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [65]:
df_wednesday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [66]:
df_wednesday2["Label"].unique()

array(['Benign', 'DDOS attack-LOIC-UDP', 'DDOS attack-HOIC'], dtype=object)

In [67]:
print(df_wednesday2["Label"].value_counts()[['Benign']].sum())
print(df_wednesday2["Label"].value_counts()[['DDOS attack-LOIC-UDP']].sum())
print(df_wednesday2["Label"].value_counts()[['DDOS attack-HOIC']].sum())

360833
1730
686012

### 2- Removing row with erroneous 'Label' label

In [ ]:
# Remove erroneous 'Label' row
df_wednesday2.drop(df_wednesday2.loc[df_wednesday2["Label"] == "Label"].index, inplace=True)

In [ ]:
df_wednesday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,...,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,...,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,17,22/02/2018 09:57:34,61898,2,2,78,254,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048571,1500,6,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,...,20,0.0,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign
1048572,53,17,22/02/2018 03:52:37,642,1,1,39,67,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048573,53,17,22/02/2018 09:40:42,78472,1,1,32,121,32,32,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048574,3389,6,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [ ]:
df_wednesday2.replace(to_replace=['DDOS attack-LOIC-UDP'], value="Malicious", inplace=True)
df_wednesday2.replace(to_replace=['DDOS attack-HOIC'], value="Malicious", inplace=True)

In [ ]:
df_wednesday2

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,...,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,...,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,...,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,17,22/02/2018 09:57:34,61898,2,2,78,254,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048571,1500,6,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,...,20,0.0,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign
1048572,53,17,22/02/2018 03:52:37,642,1,1,39,67,39,39,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048573,53,17,22/02/2018 09:40:42,78472,1,1,32,121,32,32,...,8,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
1048574,3389,6,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,...,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign

In [ ]:
df_wednesday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
print(df_wednesday2["Label"].value_counts()[['Benign']].sum())
print(df_wednesday2["Label"].value_counts()[['Malicious']].sum())

1048213
362

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [ ]:
df_wednesday2.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [ ]:
df_wednesday2["Protocol"].unique()

array([ 6, 17,  0])

In [ ]:
df_wednesday2 = pd.get_dummies(df_wednesday2, columns=['Protocol'], drop_first=True)
df_wednesday2

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,22,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,106.3,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign,1,0
1,34989,22/02/2018 08:26:24,790,2,0,848,0,848,0,424.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,1,0
2,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign,0,1
3,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign,0,1
4,500,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,500.0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,22/02/2018 09:57:34,61898,2,2,78,254,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,0,1
1048571,1500,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,0.0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,Benign,1,0
1048572,53,22/02/2018 03:52:37,642,1,1,39,67,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,0,1
1048573,53,22/02/2018 09:40:42,78472,1,1,32,121,32,32,32.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,0,1
1048574,3389,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,143.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign,1,0

In [ ]:
# making Label column the last column again
df_wednesday2.insert(len(df_wednesday2.columns)-1, 'Label', df_wednesday2.pop('Label'))

In [ ]:
df_wednesday2

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,22,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,106.3,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,34989,22/02/2018 08:26:24,790,2,0,848,0,848,0,424.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,500,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,500.0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,22/02/2018 09:57:34,61898,2,2,78,254,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,1500,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,0.0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,53,22/02/2018 03:52:37,642,1,1,39,67,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,53,22/02/2018 09:40:42,78472,1,1,32,121,32,32,32.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,3389,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,143.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [ ]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [ ]:
df_wednesday2.drop(columns=columns_to_drop, inplace=True)

In [ ]:
df_wednesday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,642,1,1,39,67,39,39,39.0,0.000000,67,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 6- Dropping missing or duplicate values

In [ ]:
df_wednesday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,642,1,1,39,67,39,39,39.0,0.000000,67,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

In [ ]:
df_wednesday2["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday2.drop_duplicates(inplace=True)

In [ ]:
df_wednesday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [ ]:
print(df_wednesday2["Label"].value_counts()[['Benign']].sum())
print(df_wednesday2["Label"].value_counts()[['Malicious']].sum())

830547
338

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [ ]:
df_wednesday2.replace(to_replace="Benign", value=0, inplace=True)
df_wednesday2.replace(to_replace="Malicious", value=1, inplace=True)

In [ ]:
df_wednesday2

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [ ]:
print(df_wednesday2["Label"].value_counts()[[0]].sum())
print(df_wednesday2["Label"].value_counts()[[1]].sum())

830547
338

### 9- Saving dataset

In [ ]:
df_wednesday2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830885 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      830885 non-null  int64
 1   Tot Fwd Pkts       830885 non-null  int64
 2   Tot Bwd Pkts       830885 non-null  int64
 3   TotLen Fwd Pkts    830885 non-null  int64
 4   TotLen Bwd Pkts    830885 non-null  int64
 5   Fwd Pkt Len Max    830885 non-null  int64
 6   Fwd Pkt Len Min    830885 non-null  int64
 7   Fwd Pkt Len Mean   830885 non-null  float64
 8   Fwd Pkt Len Std    830885 non-null  float64
 9   Bwd Pkt Len Max    830885 non-null  int64
 10  Bwd Pkt Len Min    830885 non-null  int64
 11  Bwd Pkt Len Mean   830885 non-null  float64
 12  Bwd Pkt Len Std    830885 non-null  float64
 13  Flow IAT Mean      830885 non-null  float64
 14  Flow IAT Std       830885 non-null  float64
 15  Flow IAT Max       830885 non-null  int64
 16  Flow IAT Min       830885 non-null  int64
 17  Fwd IAT Tot        830885 non-null  int64
 18  Fwd IAT Mean       830885 non-null  float64
 19  Fwd IAT Std        830885 non-null  float64
 20  Fwd IAT Max        830885 non-null  int64
 21  Fwd IAT Min        830885 non-null  int64
 22  Bwd IAT Tot        830885 non-null  int64
 23  Bwd IAT Mean       830885 non-null  float64
 24  Bwd IAT Std        830885 non-null  float64
 25  Bwd IAT Max        830885 non-null  int64
 26  Bwd IAT Min        830885 non-null  int64
 27  Fwd Header Len     830885 non-null  int64
 28  Bwd Header Len     830885 non-null  int64
 29  Fwd Pkts/s         830885 non-null  float64
 30  Bwd Pkts/s         830885 non-null  float64
 31  Pkt Len Min        830885 non-null  int64
 32  Pkt Len Max        830885 non-null  int64
 33  Pkt Len Mean       830885 non-null  float64
 34  Pkt Len Std        830885 non-null  float64
 35  Pkt Len Var        830885 non-null  float64
 36  FIN Flag Cnt       830885 non-null  int64
 37  SYN Flag Cnt       830885 non-null  int64
 38  RST Flag Cnt       830885 non-null  int64
 39  PSH Flag Cnt       830885 non-null  int64
 40  ACK Flag Cnt       830885 non-null  int64
 41  URG Flag Cnt       830885 non-null  int64
 42  CWE Flag Count     830885 non-null  int64
 43  ECE Flag Cnt       830885 non-null  int64
 44  Down/Up Ratio      830885 non-null  int64
 45  Pkt Size Avg       830885 non-null  float64
 46  Fwd Seg Size Avg   830885 non-null  float64
 47  Bwd Seg Size Avg   830885 non-null  float64
 48  Fwd Byts/b Avg     830885 non-null  int64
 49  Fwd Pkts/b Avg     830885 non-null  int64
 50  Fwd Blk Rate Avg   830885 non-null  int64
 51  Bwd Byts/b Avg     830885 non-null  int64
 52  Bwd Pkts/b Avg     830885 non-null  int64
 53  Bwd Blk Rate Avg   830885 non-null  int64
 54  Subflow Fwd Pkts   830885 non-null  int64
 55  Subflow Fwd Byts   830885 non-null  int64
 56  Subflow Bwd Pkts   830885 non-null  int64
 57  Subflow Bwd Byts   830885 non-null  int64
 58  Init Fwd Win Byts  830885 non-null  int64
 59  Init Bwd Win Byts  830885 non-null  int64
 60  Fwd Act Data Pkts  830885 non-null  int64
 61  Fwd Seg Size Min   830885 non-null  int64
 62  Active Mean        830885 non-null  float64
 63  Active Std         830885 non-null  float64
 64  Active Max         830885 non-null  int64
 65  Active Min         830885 non-null  int64
 66  Idle Mean          830885 non-null  float64
 67  Idle Std           830885 non-null  float64
 68  Idle Max           830885 non-null  int64
 69  Idle Min           830885 non-null  int64
 70  Protocol_6         830885 non-null  uint8
 71  Protocol_17        830885 non-null  uint8
 72  Label              830885 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 458.0 MB

In [ ]:
print(df_wednesday2["Label"].value_counts()[[0]].sum())
print(df_wednesday2["Label"].value_counts()[[1]].sum())

830547
338

In [ ]:
# take dataframe of benign of the first day
df_friday9_benign =  df_wednesday2[df_wednesday2["Label"]==0]
df_friday9_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [ ]:
# take datafram of malicious of the first day
df_friday9_malicious = df_wednesday2[df_wednesday2["Label"]==1]
df_friday9_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
295,6499677,13,10,2333,4425,431,0,179.461538,177.733234,1048,...,0.0,0,0,0.0,0.0,0,0,1,0,1
296,46,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
297,6397036,4,7,372,9375,372,0,93.000000,186.000000,2920,...,0.0,0,0,0.0,0.0,0,0,1,0,1
298,6,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
299,5022507,4,4,599,364,599,0,149.750000,299.500000,364,...,0.0,0,0,0.0,0.0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,5007623,5,3,694,1903,694,0,138.800000,310.366235,1903,...,0.0,0,0,0.0,0.0,0,0,1,0,1
1677,5011797,5,3,704,2033,704,0,140.800000,314.838371,2033,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2024,5934694,21,11,5132,16976,680,0,244.380952,300.648711,1933,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2497,6860324,28,15,7294,23629,680,0,260.500000,296.445798,2521,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2824,226,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1

#### 3.3 Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

In [70]:
df_wednesday3 = pd.read_csv('/mnt/d/project-chau/dataset/cse-cic-ids108/dataset/02-28-2018.csv', low_memory=False)

In [71]:
df_wednesday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,28/02/2018 08:22:13,94658,6,7,708,3718,387,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,443,6,28/02/2018 08:22:13,206,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,445,6,28/02/2018 08:22:15,165505,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,443,6,28/02/2018 08:22:16,102429,6,7,708,3718,387,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,443,6,28/02/2018 08:22:16,167,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613066,23,6,28/02/2018 11:59:12,3,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
613067,425,6,28/02/2018 10:50:04,2,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
613068,445,6,28/02/2018 12:52:55,732728,2,2,0,0,0,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
613069,23,6,28/02/2018 11:10:50,22,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration
613070,443,6,28/02/2018 11:12:18,2,1,1,0,0,0,0,...,24,0.0,0.0,0,0,0.0,0.0,0,0,Infilteration

In [72]:
df_wednesday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [73]:
df_wednesday3["Label"].unique()

array(['Benign', 'Infilteration'], dtype=object)

In [74]:
print(df_wednesday3["Label"].value_counts()[['Benign']].sum())
# print(df_wednesday3["Label"].value_counts()[['Label']].sum())
print(df_wednesday3["Label"].value_counts()[['Infilteration']].sum())

544200
68871

In [75]:
df_wednesday3.loc[df_wednesday3["Label"] == "Label"]

Empty DataFrame
Columns: [Dst Port, Protocol, Timestamp, Flow Duration, Tot Fwd Pkts, Tot Bwd Pkts, TotLen Fwd Pkts, TotLen Bwd Pkts, Fwd Pkt Len Max, Fwd Pkt Len Min, Fwd Pkt Len Mean, Fwd Pkt Len Std, Bwd Pkt Len Max, Bwd Pkt Len Min, Bwd Pkt Len Mean, Bwd Pkt Len Std, Flow Byts/s, Flow Pkts/s, Flow IAT Mean, Flow IAT Std, Flow IAT Max, Flow IAT Min, Fwd IAT Tot, Fwd IAT Mean, Fwd IAT Std, Fwd IAT Max, Fwd IAT Min, Bwd IAT Tot, Bwd IAT Mean, Bwd IAT Std, Bwd IAT Max, Bwd IAT Min, Fwd PSH Flags, Bwd PSH Flags, Fwd URG Flags, Bwd URG Flags, Fwd Header Len, Bwd Header Len, Fwd Pkts/s, Bwd Pkts/s, Pkt Len Min, Pkt Len Max, Pkt Len Mean, Pkt Len Std, Pkt Len Var, FIN Flag Cnt, SYN Flag Cnt, RST Flag Cnt, PSH Flag Cnt, ACK Flag Cnt, URG Flag Cnt, CWE Flag Count, ECE Flag Cnt, Down/Up Ratio, Pkt Size Avg, Fwd Seg Size Avg, Bwd Seg Size Avg, Fwd Byts/b Avg, Fwd Pkts/b Avg, Fwd Blk Rate Avg, Bwd Byts/b Avg, Bwd Pkts/b Avg, Bwd Blk Rate Avg, Subflow Fwd Pkts, Subflow Fwd Byts, Subflow Bwd Pkts, Subflow Bwd Byts, Init Fwd Win Byts, Init Bwd Win Byts, Fwd Act Data Pkts, Fwd Seg Size Min, Active Mean, Active Std, Active Max, Active Min, Idle Mean, Idle Std, Idle Max, Idle Min, Label]
Index: []

[0 rows x 80 columns]

### 2- Removing row with erroneous 'Label' label

In [ ]:
# Remove erroneous 'Label' row
df_wednesday3.drop(df_wednesday3.loc[df_wednesday3["Label"] == "Label"].index, inplace=True)

In [ ]:
df_wednesday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign

### 3- Creating "Malicious" label from the "Bot", "DoS attacks-SlowHTTPTest", and "DoS attacks-Hulk" labels

In [ ]:
df_wednesday3.replace(to_replace=['Infilteration'], value="Malicious", inplace=True)

In [ ]:
df_wednesday3

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign

In [ ]:
df_wednesday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
print(df_wednesday3["Label"].value_counts()[['Benign']].sum())
print(df_wednesday3["Label"].value_counts()[['Malicious']].sum())

667626
380949

### 4- Checking "Protocol" values, and creating dummies based on the assumption that the Protocol values are categorical

In [ ]:
df_wednesday3.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [ ]:
df_wednesday3["Protocol"].unique()

array([ 0,  6, 17])

In [ ]:
df_wednesday3 = pd.get_dummies(df_wednesday3, columns=['Protocol'], drop_first=True)
df_wednesday3

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_6,Protocol_17
0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,0.000000,...,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign,0,0
1,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,0.000000,...,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign,0,0
2,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,0.000000,...,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign,0,0
3,22,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,82.600000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
4,22,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,81.642857,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,217.800000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048571,80,14/02/2018 10:53:33,117,2,0,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048572,80,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048573,80,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,0.000000,...,0.0,0,0,0.0,0.000000,0,0,Benign,1,0
1048574,443,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,54.500000,...,0.0,291569,291569,5515650.0,0.000000,5515650,5515650,Benign,1,0

In [ ]:
# making Label column the last column again
df_wednesday3.insert(len(df_wednesday3.columns)-1, 'Label', df_wednesday3.pop('Label'))

In [ ]:
df_wednesday3

,Dst Port,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,22,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,106.3,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,34989,22/02/2018 08:26:24,790,2,0,848,0,848,0,424.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,500,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,500,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,500.0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,53,22/02/2018 09:57:34,61898,2,2,78,254,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,1500,22/02/2018 04:51:29,86213373,2,0,0,0,0,0,0.0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,53,22/02/2018 03:52:37,642,1,1,39,67,39,39,39.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,53,22/02/2018 09:40:42,78472,1,1,32,121,32,32,32.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,3389,22/02/2018 04:34:32,2013403,8,7,1144,1581,677,0,143.0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 5- Dropping some columns that may be irrelevant (would require re-analysis)

In [ ]:
columns_to_drop = [
    'Dst Port',
    'Timestamp',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Flow Byts/s',  # This field had np.inf values during training, as such was removed
    'Flow Pkts/s'  # This field had np.inf values during training, as such was removed
]

In [ ]:
df_wednesday3.drop(columns=columns_to_drop, inplace=True)

In [ ]:
df_wednesday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,642,1,1,39,67,39,39,39.0,0.000000,67,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 6- Dropping missing or duplicate values

In [ ]:
df_wednesday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048572,642,1,1,39,67,39,39,39.0,0.000000,67,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

In [ ]:
df_wednesday3["Label"].unique()

array(['Benign', 'Malicious'], dtype=object)

In [ ]:
df_wednesday3.drop_duplicates(inplace=True)

In [ ]:
df_wednesday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,Benign
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,Benign
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,Benign
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,Benign
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,Benign
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,Benign

### 7- Checking distribution of labels after dropping missing or duplicate values

* Malicious: 21.260%
* Benign: 78.739%

In [ ]:
print(df_wednesday3["Label"].value_counts()[['Benign']].sum())
print(df_wednesday3["Label"].value_counts()[['Malicious']].sum())

830547
338

### 8- Replacing Benign labels with zeroes and Malicious labels with ones

In [ ]:
df_wednesday3.replace(to_replace="Benign", value=0, inplace=True)
df_wednesday3.replace(to_replace="Malicious", value=1, inplace=True)

In [ ]:
df_wednesday3

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [ ]:
print(df_wednesday3["Label"].value_counts()[[0]].sum())
print(df_wednesday3["Label"].value_counts()[[1]].sum())

830547
338

### 9- Saving dataset

In [ ]:
df_wednesday3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830885 entries, 0 to 1048574
Data columns (total 73 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flow Duration      830885 non-null  int64
 1   Tot Fwd Pkts       830885 non-null  int64
 2   Tot Bwd Pkts       830885 non-null  int64
 3   TotLen Fwd Pkts    830885 non-null  int64
 4   TotLen Bwd Pkts    830885 non-null  int64
 5   Fwd Pkt Len Max    830885 non-null  int64
 6   Fwd Pkt Len Min    830885 non-null  int64
 7   Fwd Pkt Len Mean   830885 non-null  float64
 8   Fwd Pkt Len Std    830885 non-null  float64
 9   Bwd Pkt Len Max    830885 non-null  int64
 10  Bwd Pkt Len Min    830885 non-null  int64
 11  Bwd Pkt Len Mean   830885 non-null  float64
 12  Bwd Pkt Len Std    830885 non-null  float64
 13  Flow IAT Mean      830885 non-null  float64
 14  Flow IAT Std       830885 non-null  float64
 15  Flow IAT Max       830885 non-null  int64
 16  Flow IAT Min       830885 non-null  int64
 17  Fwd IAT Tot        830885 non-null  int64
 18  Fwd IAT Mean       830885 non-null  float64
 19  Fwd IAT Std        830885 non-null  float64
 20  Fwd IAT Max        830885 non-null  int64
 21  Fwd IAT Min        830885 non-null  int64
 22  Bwd IAT Tot        830885 non-null  int64
 23  Bwd IAT Mean       830885 non-null  float64
 24  Bwd IAT Std        830885 non-null  float64
 25  Bwd IAT Max        830885 non-null  int64
 26  Bwd IAT Min        830885 non-null  int64
 27  Fwd Header Len     830885 non-null  int64
 28  Bwd Header Len     830885 non-null  int64
 29  Fwd Pkts/s         830885 non-null  float64
 30  Bwd Pkts/s         830885 non-null  float64
 31  Pkt Len Min        830885 non-null  int64
 32  Pkt Len Max        830885 non-null  int64
 33  Pkt Len Mean       830885 non-null  float64
 34  Pkt Len Std        830885 non-null  float64
 35  Pkt Len Var        830885 non-null  float64
 36  FIN Flag Cnt       830885 non-null  int64
 37  SYN Flag Cnt       830885 non-null  int64
 38  RST Flag Cnt       830885 non-null  int64
 39  PSH Flag Cnt       830885 non-null  int64
 40  ACK Flag Cnt       830885 non-null  int64
 41  URG Flag Cnt       830885 non-null  int64
 42  CWE Flag Count     830885 non-null  int64
 43  ECE Flag Cnt       830885 non-null  int64
 44  Down/Up Ratio      830885 non-null  int64
 45  Pkt Size Avg       830885 non-null  float64
 46  Fwd Seg Size Avg   830885 non-null  float64
 47  Bwd Seg Size Avg   830885 non-null  float64
 48  Fwd Byts/b Avg     830885 non-null  int64
 49  Fwd Pkts/b Avg     830885 non-null  int64
 50  Fwd Blk Rate Avg   830885 non-null  int64
 51  Bwd Byts/b Avg     830885 non-null  int64
 52  Bwd Pkts/b Avg     830885 non-null  int64
 53  Bwd Blk Rate Avg   830885 non-null  int64
 54  Subflow Fwd Pkts   830885 non-null  int64
 55  Subflow Fwd Byts   830885 non-null  int64
 56  Subflow Bwd Pkts   830885 non-null  int64
 57  Subflow Bwd Byts   830885 non-null  int64
 58  Init Fwd Win Byts  830885 non-null  int64
 59  Init Bwd Win Byts  830885 non-null  int64
 60  Fwd Act Data Pkts  830885 non-null  int64
 61  Fwd Seg Size Min   830885 non-null  int64
 62  Active Mean        830885 non-null  float64
 63  Active Std         830885 non-null  float64
 64  Active Max         830885 non-null  int64
 65  Active Min         830885 non-null  int64
 66  Idle Mean          830885 non-null  float64
 67  Idle Std           830885 non-null  float64
 68  Idle Max           830885 non-null  int64
 69  Idle Min           830885 non-null  int64
 70  Protocol_6         830885 non-null  uint8
 71  Protocol_17        830885 non-null  uint8
 72  Label              830885 non-null  int64
dtypes: float64(22), int64(49), uint8(2)
memory usage: 458.0 MB

In [ ]:
print(df_wednesday3["Label"].value_counts()[[0]].sum())
print(df_wednesday3["Label"].value_counts()[[1]].sum())

830547
338

In [ ]:
# take dataframe of benign of the first day
df_friday10_benign =  df_wednesday3[df_wednesday3["Label"]==0]
df_friday10_benign

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
0,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,...,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,1,0,0
1,790,2,0,848,0,848,0,424.0,599.626550,0,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0
2,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0
3,99745913,5,0,2500,0,500,500,500.0,0.000000,0,...,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0
4,89481361,6,0,3000,0,500,500,500.0,0.000000,0,...,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,13512,1,1,36,52,36,36,36.0,0.000000,52,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048570,61898,2,2,78,254,39,39,39.0,0.000000,127,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048571,86213373,2,0,0,0,0,0,0.0,0.000000,0,...,0.0,0,0,8.621337e+07,0.000000e+00,86213373,86213373,1,0,0
1048573,78472,1,1,32,121,32,32,32.0,0.000000,121,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,1,0
1048574,2013403,8,7,1144,1581,677,0,143.0,227.969923,1173,...,0.0,0,0,0.000000e+00,0.000000e+00,0,0,1,0,0

In [ ]:
# take datafram of malicious of the first day
df_friday10_malicious = df_wednesday3[df_wednesday3["Label"]==1]
df_friday10_malicious

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_6,Protocol_17,Label
295,6499677,13,10,2333,4425,431,0,179.461538,177.733234,1048,...,0.0,0,0,0.0,0.0,0,0,1,0,1
296,46,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
297,6397036,4,7,372,9375,372,0,93.000000,186.000000,2920,...,0.0,0,0,0.0,0.0,0,0,1,0,1
298,6,2,0,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1
299,5022507,4,4,599,364,599,0,149.750000,299.500000,364,...,0.0,0,0,0.0,0.0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,5007623,5,3,694,1903,694,0,138.800000,310.366235,1903,...,0.0,0,0,0.0,0.0,0,0,1,0,1
1677,5011797,5,3,704,2033,704,0,140.800000,314.838371,2033,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2024,5934694,21,11,5132,16976,680,0,244.380952,300.648711,1933,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2497,6860324,28,15,7294,23629,680,0,260.500000,296.445798,2521,...,0.0,0,0,0.0,0.0,0,0,1,0,1
2824,226,2,1,0,0,0,0,0.000000,0.000000,0,...,0.0,0,0,0.0,0.0,0,0,1,0,1

### 4- Sum data for dataset for training and make final dataset csv file

In [78]:
# check again number of each attacks in 10 days

# 1. benign - ...
print("Number of benign in the first day (it must be ... ) : ",df_friday1_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 1. attack - ...
print("Number of attacks in the first day (it must be ...) : ",df_friday1_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 2. benign - ....
print("Number of benign in the 2nd day (it must be ...) : ",df_friday2_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 2. attack - ...
print("Number of attack in the 2nd day (it must be ...) : ",df_friday2_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 3. benign - ...
print("Number of benign in the 3rd day (it must be ...) : ",df_friday3_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 3. attack - ...
print("Number of attack in the 3rd day (it must be ...) : ",df_friday3_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 4. benign - ...
print("Number of benign in the 4th day (it must be ... ) : ",df_friday4_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 4. attack - ...
print("Number of attacks in the 4th day (it must be ...) : ",df_friday4_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 5. benign - ....
print("Number of benign in the 5th day (it must be ...) : ",df_friday5_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 5. attack - ...
print("Number of attack in the 5th day (it must be ...) : ",df_friday5_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 6. benign - ...
print("Number of benign in the 6th day (it must be ...) : ",df_friday6_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 6. attack - ...
print("Number of attack in the 6th day (it must be ...) : ",df_friday6_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 7. benign - ...
print("Number of benign in the 7th day (it must be ... ) : ",df_friday7_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 7. attack - ...
print("Number of attacks in the 7th day (it must be ...) : ",df_friday7_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 8. benign - ....
print("Number of benign in the 8th day (it must be ...) : ",df_friday8_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 8. attack - ...
print("Number of attack in the 8th day (it must be ...) : ",df_friday8_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 9. benign - ...
print("Number of benign in the 9th day (it must be ...) : ",df_friday9_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 9. attack - ...
print("Number of attack in the 9th day (it must be ...) : ",df_friday9_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

# 10. benign - ...
print("Number of benign in the 10th day (it must be ... ) : ",df_friday10_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

# 10. attack - ...
print("Number of attack in the 10th day (it must be ...) : ",df_friday10_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

Number of benign in the first day (it must be 63489) :  63489
-----------------------------------------------------------------------------------------------
Number of bot in the first day (it must be 14310) :  14310
-----------------------------------------------------------------------------------------------

Number of Dos attacks-SlowHTTPTest in the 2nd day (it must be 69945) :  69945
-----------------------------------------------------------------------------------------------
Number of DoS attacks - Hulk in the 2nd day (it must be 23334) :  23334
-----------------------------------------------------------------------------------------------

Number of Brute Force -Web in the 3rd day (it must be 362) :  362
Number of Brute Force -Web the 7th day (it must be 249) :  249
Number of Brute Force -Web in total (it must be 611) :  611
-----------------------------------------------------------------------------------------------
Number of Brute Force -XSS in the 3rd day (it must be 151) :  151
Number of Brute Force -XSS in the 7th day (it must be 79) :  79
Number of Brute Force -XSS in total (it must be 230) :  230
-----------------------------------------------------------------------------------------------
Number of SQL Injection in the 3rd day (it must be 53) :  53
Number of SQL Injection in the 7th day (it must be 34) :  34
Number of SQL Injection in total (it must be 87) :  87
-----------------------------------------------------------------------------------------------

Number of DDoS attacks-LOIC-HTTP in the 4th day (it must be 28810) :  28810
-----------------------------------------------------------------------------------------------

Number of Infilteration in the 5th day (it must be 4049) :  4049
Number of Infilteration in the 10th day (it must be 4049) :  4049
Number of infilteration in total (it must be 8098) :  8098
-----------------------------------------------------------------------------------------------

Number of DoS attacks-GoldenEye in the 6th second day (it must be 20754) :  20754
-----------------------------------------------------------------------------------------------
Number of  DoS attacks-Slowloris in the 6th day (it must be 5495) :  5495
-----------------------------------------------------------------------------------------------

Number of FTP Brute Force in the 8th day (it must be 19336) :  19336
-----------------------------------------------------------------------------------------------
Number of SSH Brute Force in the 8th day (it must be 9380) :  9380
-----------------------------------------------------------------------------------------------

Number of  DDOS attack-LOIC-UDP in the 9th day (it must be 1730) :  1730
-----------------------------------------------------------------------------------------------
Number of DDOS attack-HOIC in the 9th day (it must be 34301) :  34301
-----------------------------------------------------------------------------------------------

In [ ]:
# in total : benign 

df_total_10_days_benign = pd.concat([df_friday1_benign, df_friday2_benign, df_friday3_benign, df_friday4_benign,\
    df_friday5_benign, df_friday6_benign,df_friday7_benign,df_friday8_benign,df_friday9_benign\
        ,df_friday10_benign], axis=0, ignore_index=True)

df_total_10_days_benign

In [ ]:
# in total : attack 

df_total_10_days_malicious = pd.concat([df_friday1_malicious, df_friday2_malicious, df_friday3_malicious,\
    df_friday4_malicious, df_friday5_malicious, df_friday6_malicious, \
        df_friday7_malicious, df_friday8_malicious, df_friday9_malicious\
        , df_friday10_malicious], axis=0, ignore_index=True)

df_total_10_days_malicious

In [79]:
print("Number of benign in 10 days (it must be ... ) : ",df_total_10_days_benign.shape[0])
print("-----------------------------------------------------------------------------------------------")

print("Number of attacks in 10 days (it must be ...) : ",df_total_10_days_malicious.shape[0])
print("-----------------------------------------------------------------------------------------------\n")

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319310,3389,6,02/03/2018 12:43:02,2264122,8,7,1144,1581.0,677,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
319311,53,17,02/03/2018 09:27:46,919,1,1,39,67.0,39,39,...,8,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
319312,3389,6,02/03/2018 12:11:45,21012043,3,4,0,0.0,0,0,...,32,1507358.5,2128278.981,3012279.0,2438.0,8998663.0,4244276.932,12000000.0,5997506.0,Benign
319313,3389,6,02/03/2018 02:03:16,1623433,8,7,1148,1581.0,677,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign
319314,3389,6,02/03/2018 03:21:33,2680524,8,7,1128,1581.0,661,0,...,20,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,Benign

In [81]:
# sum data of 10 days into one data frame

df_sum= pd.concat([df_friday1, df_friday2, df_friday3, df_wednesday1, df_wednesday2,\
                  df_wednesday3, df_thursday1, df_thursday2, \
                   df_thursday3, df_thursday4,], axis=0, ignore_index=True)
df_sum.shape[0]

299910

In [83]:
df_sum

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,0.0,0.0,0.0,0.0,0.0,Benign,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299905,80,6,21/02/2018 02:11:55,20071,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299906,80,6,21/02/2018 02:11:55,21703,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299907,80,6,21/02/2018 02:11:55,19183,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299908,80,6,21/02/2018 02:11:55,23522,3,4,312,935,312,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN
299909,80,6,21/02/2018 02:11:55,30294,2,0,0,0,0,0,...,0,0.0,0.0,0,0,DDOS attack-HOIC,NaN,NaN,NaN,NaN

In [86]:
df_sum.shape[0]

299910

In [87]:
df_sum.to_csv("processed_first_final_dataset_benign_malicious_of_10_days.csv", index=False)